### ISSUE TITLE
in_app_include/in_app_exclude params not appearing to work

### ISSUE THREAD

**Issue by RobertLucian** [getsentry/sentry-python#1027]
### Environment

How do you use Sentry?
Sentry SaaS (sentry.io)

Which SDK and version?
Version 0.20.3.

### Steps to Reproduce

We have a Python package that we distribute to our users. We need the handled/unhandled exceptions that occur inside our library to be reported to sentry. Assuming the following initialization of sentry (verbatim copy):

```python
def init_sentry(
    tags: dict = {},
    disabled: bool = False,
):
    """
    Initialize sentry. Override the default values with the following env vars:
    1. CORTEX_TELEMETRY_SENTRY_DSN
    2. CORTEX_TELEMETRY_SENTRY_ENVIRONMENT
    3. CORTEX_TELEMETRY_DISABLE
    """

    dsn = CORTEX_TELEMETRY_SENTRY_DSN
    environment = CORTEX_TELEMETRY_SENTRY_ENVIRONMENT

    if not disabled and os.getenv("CORTEX_TELEMETRY_DISABLE") is True:
        return

    if os.getenv("CORTEX_TELEMETRY_SENTRY_DSN", "") != "":
        dsn = os.environ["CORTEX_TELEMETRY_SENTRY_DSN"]

    if os.getenv("CORTEX_TELEMETRY_SENTRY_ENVIRONMENT", "") != "":
        environment = os.environ["CORTEX_TELEMETRY_SENTRY_ENVIRONMENT"]

    release = CORTEX_VERSION

    user_id = None
    client_id_file_path = pathlib.Path.home() / ".cortex" / "client-id.txt"
    if client_id_file_path.is_file():
        user_id = client_id_file_path.read_text()

    sentry_sdk.init(
        dsn=dsn,
        environment=environment,
        release=release,
        ignore_errors=[CortexBinaryException],
        attach_stacktrace=True,
        in_app_include=["cortex"],
        in_app_exclude=[""],
        integrations=[
            LoggingIntegration(event_level=None, level=None),
            ThreadingIntegration(propagate_hub=True),
        ],
    )

    if user_id:
        sentry_sdk.set_user({"id": user_id})

    for k, v in tags.items():
        sentry_sdk.set_tag(k, v)
```

The above initialization occurs when the user imports specific modules of our package. Imagine our source-code looks like:

```
# our mypackage.generic.module

init_sentry()

# a bunch of function/class definitions that we want to encompass with sentry
```

### Expected Result

Problem is that exceptions that occur outside our package are still recorded by the sentry client (hub + client + scope) that we initialized in our module(s). I tried adding the name of our package in `in_app_include`, but to no avail. We only want to capture events that happen within our package. Any idea?

**Comment by untitaker** [comment]
in_app_include/in_app_exclude are for telling Sentry which individual frames within a crash are part of the application such that Sentry can group events better into issues and remove noise from the stacktrace. It is not intended for filtering crashes and does not do that.

You cannot use the SDK in this way because it will 100% collide with a potential SDK setup done by the library user. In order to help you I need to know what you would consider a crash of your library vs a crash induced by the user, and which properties of the crash you would want to look at to figure this out:

* involved stackframes
* involved exception types
* something else?

**Comment by RobertLucian** [comment]
@untitaker assuming a package like this:
```
my-pkg
├── __init__.py
├── module_a.py
├── module_b.py
└── module_c.py
```

Let's take an example function from `module_a`.

```python
# module_a.py

# init sentry
# is this even a good place to init sentry?

def function_that_does_something(params):
  # code that at some point raises an exception (i.e. due to bad coding)

```

And then as a user, I run this:

```python
from my_pkg import module_a

module_a.function_that_does_something(params)
```

Then the unhandled exception should be reported by sentry. But if in the user's implementation (not ours) there's an exception, then sentry would not be reporting that. I think it's fair to say that users wouldn't exactly be happy if reports were issued for exceptions that had nothing to do with our stack. That would also make our job harder when going through sentry.

To add a bit more context to this, our functions can raise customized exceptions due to the user's fault when they are calling them with bad params for instance, and for that, we only need to add those exceptions to the `ignore_errors` list.

What we want to capture is the involved exception type, involved stack trace, and (maybe) the local values at the line at which the exception occurred.

Also, how do you ensure that the sentry SDK setups don't collide with a potential SDK setup done by the user?

**Comment by untitaker** [comment]
In the interest of not conflicting with application logic I believe it's best if no integrations are used at all, and all library exceptions are caught, captured and reraised manually by the user. You can do the following to initialize an SDK client without initializing integrations that register global hooks:

```
hub = sentry_sdk.Hub(sentry_sdk.Client(dsn=..., default_integrations=False, auto_enabling_integrations=False))

def public_api(f):
    def wrapper(*args, **kwargs):
        with hub:
            try:
                return f(*args, **kwargs)
            except Exception:
                sentry_sdk.capture_exception()
                raise

    return wrapper

@public_api
def function_that_does_something(params):
    ....
```

You may reenable `default_integrations` if you are missing breadcrumbs or other contextual data, but `auto_enabling_integrations` may be too invasive to be silently enabled from within some library (it attempts to import Flask, Django, ... and tries to instrument them). Neither of are supposed collide if enabled since you are using your own hub instead of using `init()`, but they can add instrumentation code to random parts of the process that may be unexpected to be done from a library.

`with hub:` sets your SDK config as *the sdk config to use* for the duration of the context manager, then restores whichever state was there before (no SDK usage at all or whatever the library user has configured). Potentially you want to use `with Hub(hub):` if your library can be called concurrently, then you get a separate breadcrumbs buffer and scope object per invocation of `function_that_does_something`.

**Comment by RobertLucian** [comment]
@untitaker this is now working! Thanks a lot!

There's one thing only. How do you make it such that the client is flushed upon the termination of the interpreter? Either when the script exits normally or when it is forcefully stopped (i.e. by an unhandled exception)?

**Comment by untitaker** [comment]
A combination of atexit stdlib module and `hub.flush()` should do the trick. Normally the default integrations take care of this for you but they only flush for the current hub, not all hubs in existence.

**Comment by RobertLucian** [comment]
Thanks! I'll close this now!
