### ISSUE TITLE
Support SOCKS proxies

### ISSUE THREAD

**Issue by Roguelazer** [getsentry/sentry-python#1049]
If pysocks is available, urllib3 supports SOCKS proxies, but you can't use the `urllib3.ProxyManager` class and must instead use `urllib3.contrib.socks.SOCKSProxyManager`. It would be very nice if `sentry_sdk.transport.HttpTransport` could detect a proxy set to `socks://` (or one of the many variants) and Do The Right Thing.

**Comment by kenoss** [comment]
I vote one.  It is great that `sentry_sdk` itself has SOCKS proxy support (integrated in the class `HttpTransport`.).

Rationale:

1. There are situations we have to use sentry under SOCKS proxy.  E.g., IoT device with restricted network access.
2. [I tried to write external class `Socks5HttpTransport`](https://github.com/kenoss/test-sentry-sdk-socks-transport), but [it's not cool to use](https://github.com/kenoss/test-sentry-sdk-socks-transport/blob/main/sentry_test/main.py#L9-L17).

And then, here's some implementation options.


## How to designate proxy URL

A. From `http_proxy`/`https_proxy` option, like `requests` and https://github.com/getsentry/sentry-python/pull/1050 .
B. From other new option like `socks_proxy`.

I guess the members of sentry prefer B because https://github.com/getsentry/sentry-python/issues/178#issuecomment-460059346 .

---

@untitaker @ahmedetefy Could you let us know your thoughts?
