### ISSUE TITLE
Add util to send user feedback

### ISSUE THREAD

**Issue by ThiefMaster** [getsentry/sentry-python#1064]
Applications which don't already use the client-side sentry SDK may want to display their own UI to send user feedback to associate with an error that was logged to sentry.

It would be nice if the [user feedback api](https://docs.sentry.io/api/projects/submit-user-feedback/) was exposed in a clean way. For example, it should automatically infer the correct host/path from the DSN.

Not sure if this doesn't actually require changes on Sentry itself... right now I don't see how one would get the data needed for `organization_slug` and `project_slug` using just the DSN...

**Comment by vagi8** [comment]
Hey I am planning to take it up. I have taken a look at the Dsn class in utils but I was unable to find a method for feedback api url. Nor I could find any organization / project slug values in the Dsn nor in Auth.  What am I missing ?

**Comment by antonpirker** [comment]
Hey @vagi8 

You are right. Right now the SDK only knows the DSN but not the `organization_slug` and `project_slug`.  I looked at how the browser JS SDK does it [1] and it seems it creates an envelope.

So I guess this is not a minor change as we thought. We will need to discuss this internally if we want to have this feature in the Python SDK.

1: https://github.com/getsentry/sentry-javascript/blob/f63036ba6d896f624328c857d2170f8a6843f5e1/packages/browser/src/client.ts#L97-L109

**Comment by antonpirker** [comment]
We discussed this internally and because this is not only about giving the user the Feddback api URL, but implementing a feature that puts user feedback in an envelope and send it to Sentry, we will not implement this right now or in the short to mid term future. We have more pressing things on our agenda. So I will close this issue.

**Comment by theCapypara** [comment]
@antonpirker Would this still be OK to contribute as a PR, or is this a feature you currently don't want implemented at all for some reason?

I'm not sure what you mean by "not only about giving the user the Feddback api URL, but implementing a feature that puts user feedback in an envelope and send it to Sentry". Isn't this also what this issue was originally about? Exposing the user feedback API via the SDK so developers can show their own forms to the users and then the SDK will send it to Sentry via the `user-feedback` api?

I would be interested in contributing such a feature, but I'm not sure what you mean about the envelope, the only thing I can find is the official API documentation (https://docs.sentry.io/api/projects/submit-user-feedback/) which I thought would be the one to use?

**Comment by theCapypara** [comment]
Nevermind, found info on the topic: https://develop.sentry.dev/sdk/envelopes/

Would a PR that does things similar to https://github.com/getsentry/sentry-javascript/pull/7729 be OK to submit?

**Comment by theCapypara** [comment]
I opened a PR to implement this: #2442
