### ISSUE TITLE
XML body in Django (DRF) is not stringified

### ISSUE THREAD

**Issue by a-martynovich** [getsentry/sentry-python#1116]
### Environment

I'm using sentry.io (SaaS) with 

- sentry-sdk 1.1.0, 
- Django 2.2 
- djangorestframework 3.12.1 
- djangorestframework-xml 2.0.0

### Steps to Reproduce

1. Add a simple endpoint
```
from rest_framework_xml.parsers import XMLParser

@api_view(["POST"])
@parser_classes((XMLParser,))
def handle_request(request):
    raise Exception("error!")
```
2. POST some valid XML to that endpoint, such as 
```
<?xml version="1.0" encoding="UTF-8"?>
<root></root>
```
3. Find the exception reported to Sentry on sentry.io

### Expected Result

Sentry should show the actual Body of the request (the XML document).

### Actual Result

The value of "Body" on Sentry page is `"<xml.etree.ElementTree.ElementTree object at 0xSOMEADDRESS>"`

**Comment by targhs** [comment]
@a-martynovich i was trying to reproduce this. Could you help me where exactly can i find the request body on Sentry page.

**Comment by antonpirker** [comment]
Hey @a-martynovich 

Better late then never. I have looked into this.
We do not record raw body data, because the chance that sensitive data is leaked is to big. (Our servers do sensitive data trimming in the data it receives, but this works only really well for json data, so XML body data is not sent at all.)

Sorry that we can not help you here.
