### ISSUE TITLE
Support Sanic 21.03

### ISSUE THREAD

**Issue by robd003** [getsentry/sentry-python#1128]
Could you guys support the latest version of Sanic?

**Comment by SaidBySolo** [comment]
#1066 Maybe can support

**Comment by SaidBySolo** [comment]
I recently found it in the documentation.

It seems that the latest version of sanic is no longer supported.

https://docs.sentry.io/platforms/python/guides/sanic/

**Comment by codesync-admin** [comment]
@SaidBySolo , Based on that page, that's due to a two-year old issue about Sanic not having a consistent deprecation policy for LTS releases. I'm not sure if that's still the case now (July 2021).

https://github.com/sanic-org/sanic/issues/1532 

Hopefully Sentry can revisit this! (And merge in your PR!)

**Comment by codesync-admin** [comment]
@ahmedetefy Thanks -- can you update the docs as well please? :D

https://docs.sentry.io/platforms/python/guides/sanic/

(Assume that the integration's been tested and all of course)

**Comment by ahmedetefy** [comment]
Yes we can. Thanks for the reminder :)
