### ISSUE TITLE
Name 'Hub' is not defined when using with Sanic

### ISSUE THREAD

**Issue by cnicodeme** [getsentry/sentry-python#1240]
Hi!

When trying to run Sentry with Sanic, I get the following error:

```
Traceback (most recent call last):
  File "/var/www/project/env/lib/python3.10/site-packages/sanic/http.py", line 141, in http1
    await self.protocol.request_handler(self.request)
  File "sentry_handle_request", line 3, in sentry_handle_request
    import logging
NameError: name 'Hub' is not defined
```

This causes the Sanic server to not work properly.

Here's the versions I'm using:

**Sanic** = 21.9.1
**Sentry-sdk** = 1.4.3

Happy to provide any other details if needed.

**Comment by cnicodeme** [comment]
Well, adding `from sentry_sdk.hub import Hub` directly inside `async def sentry_handle_request(self, request, *args, **kwargs):` solve the issue, but raise another problem, with `SanicIntegration` not being defined.

There is clearly an issue with the Sanic integration.

**Comment by AbhiPrasad** [comment]
Yup can confirm, see related Sanic issue: https://github.com/sanic-org/sanic/issues/2250. Tests are also failing on master because of this.

**Comment by ahopkins** [comment]
I'm only aware of this at the moment: https://github.com/getsentry/sentry-python/pull/1212

Full disclosure I have not looked at this issue so it may be unrelated.

**Comment by ahopkins** [comment]
@AbhiPrasad I am looking at this issue now. The import `Hub` issue is **NOT** related to the problem that I solved in #1212. I am also interested to know if this is just Sanic 21.9, but I think it would impact 21.6 and 21.3 integrations.

TBH, I think part of the problem is that this integration is _SUPER_ hacky. It is not at all the recommended way to handle custom exception logic, and I am not surprised that it is broken. With that said, I am not :100: confident that I am aware enough about Sentry internals to make a complete correction. But, if the project maintainers here are willing to work with me here, I can get a nicer integration for Sanic v21+ that does not include monkeypatching.

**Comment by AbhiPrasad** [comment]
@ahopkins more than happy to give you any support you need here, in addition we can also take on updating the docs/writing tests so you can focus on whatever improvements you want to make.

We’ll review #1212 ASAP, thanks for all your help!

**Comment by ahopkins** [comment]
After I saw the contribution guidelines about 0 configuration, I see why the integration is the way it is. I am working on a version that should be much safer, but probably no less hacky :laughing:

**Comment by ahopkins** [comment]
Thanks @AbhiPrasad. Moving the conversation to #1212
