### ISSUE TITLE
`DjangoIntegration` together with `LoggingIntegration`: drawbacks?

### ISSUE THREAD

**Issue by strogonoff** [getsentry/sentry-python#1316]
I use `DjangoIntegration`, but I don’t think it captures random log warnings. I intend to add `LoggingIntegration` with appropriate log level.

Is it correct that `DjangoIntegration` cannot itself be configured to capture `log.warning()`s? Would using both `DjangoIntegration` and `LoggingIntegration` with appropriate log level config result in duplicate events being pushed to Sentry or any other drawbacks?

The project already configures a global `LOGGING` Django setting with a handler that prints warnings to console, not sure if `LOGGING` affects Sentry’s `DjangoIntegration` though (I find docs slightly lacking on that, or I missed the relevant part).

**Comment by sl0thentr0py** [comment]
Hi @strogonoff,

Are you manually overriding integrations in your sentry init or using the defaults? By default, both  `DjangoIntegration` and `LoggingIntegration` in a django app will be turned on and are meant to be used out of the box with each other as they serve separate purposes.

> Is it correct that DjangoIntegration cannot itself be configured to capture log.warning()s?

Yes that is correct. The `DjangoIntegration` does things like wrap WSGI/middleware etc and capture exceptions/trace transactions within the django request/response cycle.
The `LoggingIntegration` takes logs above your defined level and adds those to breadcrumbs/exceptions.

>  result in duplicate events

No, it shouldn't because we have a `DedupeIntegration` turned on by default that filters duplicated exceptions.
One caveat, we ignore the following 3 loggers in django due to spammy reasons, so stuff from those won't show up in sentry.
```
        ignore_logger("django.server")
        ignore_logger("django.request")
        ignore_logger("django.db.backends")
```

**Comment by strogonoff** [comment]
> Are you manually overriding integrations in your sentry init or using the defaults?

We’re doing something along the lines of

```
    sentry_warning_logging = LoggingIntegration(
         level=logging.INFO,
         event_level=logging.WARNING
    )
    sentry_sdk.init(
        dsn=environ.get("SENTRY_DSN"),
        integrations=[DjangoIntegration(), sentry_warning_logging],
        server_name=...
```

Thank you, very informative. Sounds like it’s OK to keep both.
