### ISSUE TITLE
Using `push_scope()` as a context manager gives typing errors

### ISSUE THREAD

**Issue by Kjir** [getsentry/sentry-python#1469]
### How do you use Sentry?

Sentry Saas (sentry.io)

### Version

1.5.12

### Steps to Reproduce

Use `push_scope()` as context manager:

```python
with push_scope() as scope:
  ...
```

### Expected Result

No type error is reported

### Actual Result

When type-checking this code with `pyright` we get an error:

![image](https://user-images.githubusercontent.com/64094/174272453-20763c8b-4dfd-451f-9cb7-9c06991773be.png)

And this is because `push_scope()` can return `None`:
![image](https://user-images.githubusercontent.com/64094/174272570-5a0bde21-79a5-4556-9720-1f05f29eb345.png)

**Comment by antonpirker** [comment]
Hey @Kjir 
Thanks for writing!

Only if you give a `callback` to `push_scope()` it can return a null value. (See https://github.com/getsentry/sentry-python/blob/master/sentry_sdk/hub.py#L539-L546 ) 

So in your case it will never return `None`.

So maybe `pyright` gets confused by our type definitions (but we have to do them that way, because we still have to support Python 2.7)

I guess the easiest solution is to tell pyright to ignore this error.

**Comment by Kjir** [comment]
You already have type hints in comments, so python 2.7 support is there.
I believe you have a problem with the overloads:

```python
@overload
def push_scope():  # noqa: F811
    # type: () -> ContextManager[Scope]
    pass


@overload
def push_scope(  # noqa: F811
    callback,  # type: Callable[[Scope], None]
):
    # type: (...) -> None
    pass


@hubmethod
def push_scope(  # noqa: F811
    callback=None,  # type: Optional[Callable[[Scope], None]]
):
    # type: (...) -> Optional[ContextManager[Scope]]
    return Hub.current.push_scope(callback)
```

The first two are correct, but the third one defines the return type as `Optional[ContextManager[Scope]]` and that's probably why `pyright` sees this as a possibility. The actual implementation should have no type hints: https://docs.python.org/3/library/typing.html#typing.overload
