### ISSUE TITLE
Event breadcrumbs have incompatible types between Python and JS SDKs

### ISSUE THREAD

**Issue by alexmojaki** [getsentry/sentry-python#1536]
### How do you use Sentry?

Sentry Saas (sentry.io)

### Version

1.9.0

### Steps to Reproduce

Background: I use `sentry_sdk` in Python running in the browser with Pyodide to collect a serialised Sentry event about a Python exception without actually sending it, because Python code for sending network requests doesn't work in the browser. The code for that is here: https://github.com/alexmojaki/futurecoder/blob/e09f016bd69f893d3eb81e1a4bfa804953aedb4e/core/utils.py#L205-L225 . The event is returned to JS which sends it to the server using `Sentry.captureEvent`. I'm `@sentry/react`, and it and all its dependencies like `@sentry/browser` are on version 7.8.1.

In summary:

1. In Python, use `sentry_sdk.init()` to set a custom transport to intercept events.
2. Then `sentry_sdk.capture_exception()` to collect an event, but don't send it.
3. Pass the captured event to `Sentry.captureEvent()` in JS.

### Expected Result

The event is captured successfully and can be viewed on sentry.io. This has in fact been working great for a while, and the UI shows me info from both the JS and Python SDKs in one event.

### Actual Result

`Sentry.captureEvent()` in JS runs into a `TypeError: (e.breadcrumbs || []) is not iterable`, which itself actually gets captured by Sentry and sent instead:

![Screenshot from 2022-08-03 15-16-11](https://user-images.githubusercontent.com/3627481/182617318-a014d85e-82b6-4fb6-8329-55b7ba9d1993.png)

The problem is that in the Python event, `breadcrumbs` is a `dict` with a key `values` mapping to a list. But JS expects `breadcrumbs` to just be the list (array) rather than a dict (object). If I set `event.breadcrumbs = event.breadcrumbs.values` in JS, then everything goes back to working perfectly. However this doesn't mean much since in this case `event.breadcrumbs` is just `{values: []}`. I don't know if there are sometimes keys other than `values`, or if the lists themselves are also sometimes incompatible between the SDKs.

I don't know to what extent the different SDKs are meant to have compatible schema, but it seems like it's been working well so far and it'd be a pity to lose that. Also, I don't know if this issue belongs here or in a JS repo.

**Comment by sl0thentr0py** [comment]
hey @alexmojaki this is a really unconventional use case, but bonus points for creativity! I'm surprised the rest of the SDK works at all since we never tested in webassembly before. ^^

> I don't know to what extent the different SDKs are meant to have compatible schema, but it seems like it's been working well so far and it'd be a pity to lose that. Also, I don't know if this issue belongs here or in a JS repo.

Yes, there might be some inconsistencies between SDKs in this regard, because our [event schema](https://develop.sentry.dev/sdk/event-payloads/types/) allows both a [direct list of objects or nested under `values`](https://develop.sentry.dev/sdk/event-payloads/exception/) as noted for `exception` here. The same holds for `breadcrumbs`.
> The exception attribute should be an object with the attribute values containing a list of one or more values that are objects in the format described below. Alternatively, the exception attribute may be a flat list of objects in the format below.

Unfortunately, this really counts as an _unsupported_ use case so you'll just have to deal with the inconsistencies on your end, sorry! If you need me to confirm something about the schema, you can ask me here again, but I'll close this issue.
