### ISSUE TITLE
Minor update 1.9.6 introduces breaking change

### ISSUE THREAD

**Issue by sileht** [getsentry/sentry-python#1592]
### How do you use Sentry?

Sentry Saas (sentry.io)

### Version

1.9.6

### Steps to Reproduce

* Install 1.9.5
* Follow https://docs.sentry.io/platforms/python/guides/asgi/
* Update to 1.9.6

And got the following exception:

```
RuntimeError: The Sentry Python SDK can now automatically support ASGI frameworks like Starlette and FastAPI.
Please remove 'SentryAsgiMiddleware' from your project.
See https://docs.sentry.io/platforms/python/guides/asgi/ for more information.
```

### Expected Result

* The `SentryAsgiMiddleware` middleware still working, or at least a noop object printing/logging a deprecation warning
* A notice that the object will be removed in a future release
* A SemVer major version bump
* A updated documentation and with a section about the library API change and the object deprecation

### Actual Result

* project code is not loading anymore
* No deprecation warning
* Minor SemVer change with breaking change
* Documentation still refers to `SentryAsgiMiddleware`

**Comment by antonpirker** [comment]
Hey @sileht !

Thanks for the feedback. Yes, we could have done better here with out communication.
We just made it easier for projects using Starlette or FastAPI to include Sentry. The `SentryAsgiMiddleware` is only deprecated to use if you also use a supported ASGI framwork (because our ASGI framework integrations enable `SentryAsgiMiddleware` internally)

Maybe the hint on top of https://docs.sentry.io/platforms/python/guides/asgi/ should be more prominent, so people know to use the integrations? Do you think this could improve the situation?

**Comment by sileht** [comment]
I just didn't expect an application to not start anymore with a library minor update.

Libraries usually print warning that something should not be used anymore and will break at version X.X.X so developers can plan the change.

The doc looks ~ fine even though it's not clear it's a deprecation when your use FastAPI

The release changelog does not look great too
* `Auto-enable Starlette and FastAPI (https://github.com/getsentry/sentry-python/pull/1533) by @antonpirker`

I would expect something like:
* `If you use SentryAsgiMiddleware and FastAPI, your application will break please follow [link-to deprecation doc] to update your code.`

**Comment by antonpirker** [comment]
We are working on a fix for this. Stick with us.

**Comment by antonpirker** [comment]
A fix is deploying right now. Sorry for any inconveniences you had @sileht , @daniel-deci, @martolini and others!

**Comment by antonpirker** [comment]
Here you go: https://github.com/getsentry/sentry-python/releases/tag/1.9.7
