### ISSUE TITLE
Add a timeout to `serialize`

### ISSUE THREAD

**Issue by andyljones** [getsentry/sentry-python#1741]
### Problem Statement

We use `__sentry_repr__` on some of our classes together with `serialize`. Our setup is something like
```
def __sentry_repr__(self):
    d = self.convert_to_nested_dict()
    return sentry_sdk.serializer.serialize(d)
```
where `serialize` goes on to make many `__sentry_repr__` calls to sub-objects.

When `self` is part of a large tree of objects, this can take many minutes to run and cause exception reporting to be delayed. 

### Solution Brainstorm

We'd like to have `serialize` time out if a call is taking too long, so as not to delay exception reporting. 

The reason to prefer timeouts over depth limits or breadth limits is that it provides a guarantee about how fast the error will be reported. The tradeoff is that the reported locals will not be reliably filled, but - that seems like a worthwhile trade?

**Comment by sl0thentr0py** [comment]
hey @andyljones, sorry I'll have to reject this.

1. `__sentry_repr__` is an advanced feature for complex data structures where you just want to tell sentry how to show it in the UX
2. it in no way supports recursive calls to serialize within it
3. because the serialization itself recurses and does fairly complex truncation logic
4. re: timeouts, that would just lead to weird undefined behaviour and payloads that would randomly be dropped by ingest since they're not schema compliant, so this is also a no-go from our side

please just use `__sentry_repr__` without recursion or just use our normal serialization.
