### ISSUE TITLE
MongoDb integranion percents in description in traces

### ISSUE THREAD

**Issue by tonal** [getsentry/sentry-python#1784]
### How do you use Sentry?

Self-hosted/on-premise

### Version

1.11.1

### Steps to Reproduce

1. Install PyMongoIntegration and enable trace:
```
sentry_sdk.init(
      dsn=dsn, integrations=[PyMongoIntegration()], traces_sample_rate=1.)
```
2. See **Performance**
```
Description | find {'find': 'goods', 'filter': {'_id': '%s'}}
```
```
Description | getMore {'getMore': '%s', 'collection': '%s'}
```
![image](https://user-images.githubusercontent.com/316216/207520866-be348224-8187-4946-9519-12ec5b23973d.png)

### Expected Result

```
Description | find {'find': 'goods', 'filter': {'_id': 159638}}
```
```
Description | getMore {'getMore': 1000, 'collection': 'goods'}
```

### Actual Result

```
Description | find {'find': 'goods', 'filter': {'_id': '%s'}}
```
```
Description | getMore {'getMore': '%s', 'collection': '%s'}
```
![image](https://user-images.githubusercontent.com/316216/207520866-be348224-8187-4946-9519-12ec5b23973d.png)

**Comment by cleptric** [comment]
This is by design, as your query parameters could contain PII (Personal Identifiable Information) or other sensitive data like auth tokens.

See https://github.com/getsentry/sentry-python/blob/master/sentry_sdk/integrations/pymongo.py#L133

You can opt out of this behavior by setting the [send_default_pii](https://docs.sentry.io/platforms/python/configuration/options/#send-default-pii) options flag to `True`.

**Comment by sl0thentr0py** [comment]
closing as answered
