### ISSUE TITLE
Consider making ``Transporter`` abstract with all methods returning ``NotImplementedError``

### ISSUE THREAD

**Issue by DanielNoord** [getsentry/sentry-python#1803]
### Problem Statement

We used multiple transporter to send to different DSN, this was the previously recommended way to solve this:
https://github.com/getsentry/sentry-python/issues/198#issuecomment-478392304

The new suggestion (https://github.com/getsentry/sentry-python/discussions/1521) doesn't really work for us as it would be infeasible to start contextmanagers everywhere we use the separate loggers.

However, bumping our `sentry-sdk` has introduced subtle issues as our `TransporterProxy` doesn't implement all methods.
Previously all methods were "abstract" but with https://github.com/getsentry/sentry-python/commit/a6a1be305cc40468670156f78e10092c1b78ea60 they no longer are.

I am asking to make the transporter abstract so that we get better warnings to implement new methods when they get added. I think other users will also benefit from this as it seems like a common use case and users might have followed the same recommendation.

### Solution Brainstorm

I am open to making the PR myself but I'd like approval of maintainers first.

**Comment by sl0thentr0py** [comment]
great suggestion @DanielNoord, thank you!
I agree that making the `Transport` contract explicit is helpful.

cc @antonpirker whenever we do this, we also need to clean up [`FunctionTransport`](https://github.com/getsentry/sentry-python/blob/e2e0de10a0614bb8fb8768757849dce584f381cf/sentry_sdk/transport.py#L501-L514) since right now it only implements `capture_event` and is broken.

Also related to [Custom Transports](https://github.com/getsentry/sentry-python/discussions/1484).
