### ISSUE TITLE
capture_exception and capture_message would be improved with shorthand syntax

### ISSUE THREAD

**Issue by beaugunderson** [getsentry/sentry-python#185]
We used the `extra` parameter to `captureException` and `captureMessage` in raven quite often, and what took one line now takes a minimum of three (plus one line for each attribute of the extra object), plus a level of indentation:

```python
captureMessage('something', extra={'a': 1, 'b': 2})

# vs...
with push_scope() as scope:
    scope.set_extra('a', 1)
    scope.set_extra('b', 2)
    capture_message('something')
```

**Comment by untitaker** [comment]
This was a conscious decision. Generally the idea is that extra data should be applied to entire codeblocks instead of single capture/logging statements. The old Raven SDK encouraged both but often there's no reason for the latter.

The one thing where it truly gets annoying is when you migrate from raven to the new SDK and don't want to refactor that part of your code. But I imagine the solution for this is writing your own helper functions for backwards compat. At least that's what worked well for us when porting sentry itself.

**Comment by beaugunderson** [comment]
fair enough, I can write a wrapper method :)
