### ISSUE TITLE
Warning about uwsgi threads disabled

### ISSUE THREAD

**Issue by Ashish-Bansal** [getsentry/sentry-python#187]
Hi,

```
/root/.virtualenvs/venv/lib/python3.6/site-packages/sentry_sdk/_compat.py:78: 

Warning: We detected the use of uwsgi with disabled threads.  This will cause issues with the transport you are trying to use.  Please enable threading for uwsgi.  (Enable the "enable-threads" flag).
  "We detected the use of uwsgi with disabled threads.  "
```

I got this message from the library. I don't want to enable threads intentionally because it will affect some other library. 

I would like to know what kinda issues will happen with disabling threading ?

Regards,
Ashish Bansal

**Comment by untitaker** [comment]
Hi @Ashish-Bansal, we need threads because otherwise the SDK would make your application slower whenever you try to send an event. Concretely we send events on a different thread instead of blocking calls to `capture_message` and `capture_exception`.

A library that has problems with threading should be fixed. We have #125 but it's not a priority right now.
