### ISSUE TITLE
`responses` in tests/integrations/stdlib/test_httplib.py does not intercept urlopen requests

### ISSUE THREAD

**Issue by alexmv** [getsentry/sentry-python#1920]
### How do you use Sentry?

Sentry Saas (sentry.io)

### Version

main (1.15.0-16-g2d24560)

### Steps to Reproduce

1. Observe the lack of `@responses.activate` decorator on `test_crumb_capture` in `tests/integrations/stdlib/test_httplib.py`
2. Apply the following patch:
```diff
diff --git a/tests/integrations/stdlib/test_httplib.py b/tests/integrations/stdlib/test_httplib.py
index a66a20c..f1c5dd4 100644
--- a/tests/integrations/stdlib/test_httplib.py
+++ b/tests/integrations/stdlib/test_httplib.py
@@ -31,7 +31,7 @@ from sentry_sdk.integrations.stdlib import StdlibIntegration
 def test_crumb_capture(sentry_init, capture_events):
     sentry_init(integrations=[StdlibIntegration()])

-    url = "http://example.com/"
+    url = "http://example.com/404/"
     responses.add(responses.GET, url, status=200)

     events = capture_events()
```
3. `pytest tests/integrations/stdlib/test_httplib.py`
4. See the test fails _because it's actually talking to the webserver on `example.com`_.

Ref https://github.com/getsentry/responses/issues/373.

### Expected Result

Tests mock their network accesses.

### Actual Result

Tests require connectivity to `http://example.com/` to run

**Comment by alexmv** [comment]
I ran into this when trying to add support for proxy information in spans.  I'd love to submit a patch to add the functionality, but I'm a bit blocked on doing so until the tests support mocking our their network connections so we can differentiate between talking to the proxy and talking to the end host.

**Comment by antonpirker** [comment]
Hey @alexmv 
Thanks for bringing this up!

I have looked into the test and you are of course right. But when reading the test I was thinking, that checking for breadcrumb creation in the tests of the stdlib/httplib integration does not make sense at all, because the integration just creates a span. And the breadcrumb is created in `tracing_utils.py` when the span is finished in `tracing.py`. (have a look at the `maybe_create_breadcrumbs_from_span` function)

So I guess I will remove this test altogether and test for breadcrumb creation somewhere else.

Does this block you in any way?
