### ISSUE TITLE
No Longer loading environment and release from environment variable

### ISSUE THREAD

**Issue by cancan101** [getsentry/sentry-python#193]
The [old Python lib loaded `environment` and `release` from the environment](https://github.com/getsentry/raven-python/blob/03559bb05fd963e2be96372ae89fb0bce751d26d/raven/base.py#L198-L202) however this lib does not appear to do that. Further there is no mention of that change in the docs nor a clear suggestion for a migration path.

**Comment by untitaker** [comment]
About the docs: Yeah we should set up some kind of migration guide from the old SDK to the new one. I don't think mentioning the differences to Raven throughout the docs is a good idea.

`environment` and `release` are still arguments to the client, so you can do this:

```
init(__dsn__, environment=os.environ.get("SENTRY_ENVIRONMENT"), release=os.environ.get("SENTRY_RELEASE"))
```

**Comment by untitaker** [comment]
With 0.7.4 (not yet released) the workaround should no longer be necessary.

**Comment by cancan101** [comment]
@untitaker what about falling back to `HEROKU_SLUG_COMMIT` for the release?

**Comment by untitaker** [comment]
@cancan101 that fell under the radar, sorry!

I don't think we want to do this in the core client, but possibly as integration you have to explicitly enable. Not because writing a new class just for a single envvar is great, but because I want to avoid having a lot of env-specific oneliners on `Client`.
