### ISSUE TITLE
Improve Backpressure Management

### ISSUE THREAD

**Issue by smeubank** [getsentry/sentry-python#2095]
Sentry SDKs should be able to sample for transactions (performance events) at 100%. 

Meaning the the developer setting up their Sentry service(s) for [Sentry Performance](https://docs.sentry.io/platforms/python/performance/) should be able to set `traces_sample_rate=1.0,` and not worry that the SDK will have some significant impact on their applications performance, and definitely not that the service could be brought down by the SDK.

Hight throughput backend environments are typically the only services which face this concern, and then it is really only very large high traffic evironment faced by large business and enterprises.

### Proposal:

1. find ways to improve the SDK, find and fix different bottlenecks
2. fail safe(s): SDK should be able to detect when there is failure imminent, or even a significant degradation to the host service and shut down
3. Agents (sidecar): Should an agent be required to truly meet this goal: what changes are necessary to achieve that
  - for example HTTP requests ultimately make up a huge chunk of the OH caused by the SDks. Should we switch to a different communication method with an agent approach
  - Would there be an agent mode of the SDK(s)? When relay is running locally then switch from HTTP. Otherwise works as usual (just as suggestion)

### Outcome:

Sentry.io python services sample at 100%

**Comment by danielkhan** [comment]
For context, we need 100% because it was the main reason for introducing server-side sampling and metrics extraction in the first place. 
If there is sampling on the client, all the metrics we extract in Relay are off by the client-side sampling rate.

Let's make _"As a user; I want metrics to be always accurate."_ the primary use case, as this can lead to other solutions than a sidecar. 

E.g. 
* we _could_ extract metrics on the SDK 
* we _could_ report the client-side sampling rate with the data and extrapolate later in the pipeline

I'm not saying that these are viable solutions, but let's keep our eyes on the goal, which is accurate metrics.

**Comment by antonpirker** [comment]
Also related: https://github.com/getsentry/team-webplatform-meta/issues/50

**Comment by sl0thentr0py** [comment]
keeping this open for now till we test in sentry, 
next steps are 
* deploy https://github.com/getsentry/sentry/pull/52104 and bump multiplier and monitor / revert if things start going bad
* final goal is to remove all custom sample rates on sentry
