### ISSUE TITLE
Async Methods profiling in python?

### ISSUE THREAD

**Issue by DilLip-Chowdary-Codes** [getsentry/sentry-python#2124]
### Problem Statement

I've tried Sentry profiling, and observed that async methods are not being tracked in profiling, is that expected?

I've tried in Django application which is deployed in AWS Lambda, enabled sentry monitoring with below snippet

```py
sentry_sdk.init(
    dsn=os.environ.get("SENTRY_DSN"),
    environment=os.environ.get('STAGE', 'local'),
    integrations=[sentry_logging, AwsLambdaIntegration()],
    release=RELEASE_VERSION,
    attach_stacktrace=True,
    profiles_sample_rate=1.0,
    traces_sample_rate=1.0,
    send_default_pii=True
)
```

### Solution Brainstorm

NA

**Comment by Zylphrex** [comment]
The profiler captures the current executing stack at regular intervals. With async methods, because they often do not remain on the stack for long periods of time, it doesn't frequently appear in the final profile.

Do you have an example application that you can share or perhaps a profile you captured that we can take a look at to see if there's some other reason why this may be happening?
