### ISSUE TITLE
Include filename, line number (and pathname, processName, etc) in captured events

### ISSUE THREAD

**Issue by mtvx** [getsentry/sentry-python#2166]
### Problem Statement

Upgraded from the old Raven client (6.x) into Sentry SDK (1.22.2) and I'm noticing that events created via *logging instrumentation* (from a `logging.warning` statement) don't include the the details that used to exist with the Raven client:

- filename
- lineno
- pathname
- processName
- process
- thread
- threadName

### Solution Brainstorm

It would be beneficial to show at least the filename and line number, so it's easy to find from code.

Found an [old ticket](https://github.com/getsentry/sentry-python/issues/545) which explains the issue, with comment from @antonpirker:

> If you came across this Issue and want to help fixing it, please create a new Issue and link to this one. Thanks!

I'm not sure if the original ticket discussed about *stacktraces* and their line numbers (maybe?) but here it would be useful to show the same missing details for simple log statements (without stacktraces).

Do you plan to add these details back to events, and if not, what is the recommended workaround (e.g. using `before_send`)?

**Comment by szokeasaurusrex** [comment]
@mtvx Have you tried using `attach_stacktrace`? If so, what was the problem?

**Comment by tuukkamustonen** [comment]
No I have not. But according to docs, that would attach stacktrace to _all messages_, and I'd only maybe want those for warnings.

**Comment by szokeasaurusrex** [comment]
@tuukkamustonen Understood – in that case, you could still use the `attach_stacktrace` option. In order to only have the stack trace on log messages, you could remove the stack trace from any non-log messages within a [custom `before_send` callback](https://docs.sentry.io/platforms/python/configuration/options/#before-send). Something like the following pseudocode could work:

```python
# Note: this is Python-like pseudocode
sentry_sdk.init(..., attach_stacktrace=True, before_send=my_before_send)

def my_before_send(event, hint):
    if event is not logging event:
        del event["threads"]  # this is where we attach the stack trace when attach_stacktrace is enabled
    return event
```

Please let me know whether that works! Assuming it does, we are unlikely to introduce a new option that attaches stack traces to log messages only, since we already have the `attach_stacktraces` method.

**Comment by tuukkamustonen** [comment]
Thanks for the pointers. Lemme check a couple of things and get back to you a bit later.

**Comment by tuukkamustonen** [comment]
@szokeasaurusrex So, thanks for the patience.

I didn't actually test yet the `attach_stacktrace` option (too many other troubles taking attention). But I did play with Sentry a lot, and not having the source of where the log line came from is real pain.

I think problems with the `attach_stacktrace` workaround are:

1. Fingerprinting works differently once you enable stacktraces
2. You cannot remove the stacktrace only when it was automatically added. Doing `log.debug("foo")` and `log.debug("bar", exc_info=True)` and it's not possible to remove the stacktrace from foo, but leave it to bar (or is it?)
3. Stacktrace is much more heavyweight stuff, than simply including log module/line (the details in the ticket's description)

Imo, you should just include the logging information by default, or have it behind an option. I don't know the reasonins (maybe scalability, costs, etc) but from customer's perspective it would be nice to just have this as built-in, without resorting to hacks.

**Comment by szokeasaurusrex** [comment]
@tuukkamustonen, after further discussion with the team, we have decided that we will keep the logging integration as it is for now, since `attach_stacktrace` already provides the information (file name and line number) that you want, and because the concerns you have raised in your previous comment can all be worked around, as I describe below. We would only consider changing the behavior if we see more users requesting this change.

You can work around each of the concerns above as follows:

1. If fingerprinting changes in a problematic way after enabling `attach_stacktrace`, you can configure [custom "Fingerprint Rules"](https://docs.sentry.io/concepts/data-management/event-grouping/fingerprint-rules/) to change the fingerprinting behavior, as desired.
2. I am not exactly sure of what the problem is here, but `before_send` gives you full access to the event. So, for example, if you would like to remove the stack trace only from `foo`, you can check the log message on the event, and remove the stack trace if the message is `foo`.
3. Again, since you have full access to the event in `before_send`, you can remove anything from the event that you do not wish to send to Sentry. So, if you only want the file and line number, you can keep only that information and remove the rest of the stack trace from the event.

Please let me know whether you have any other concerns.
