### ISSUE TITLE
Auto enable HTTPX integrations

### ISSUE THREAD

**Issue by antonpirker** [getsentry/sentry-python#2175]
### Problem Statement

Our HTTPX integrations is not enabled by default.

### Solution Brainstorm

When httpx package is installed, the HTTPX integration should be auto enabled.

**Comment by danielkhan** [comment]
I would argue that this behavior should be the case for each platform where this is possible.
E.g., I only want to add a Node.js SDK, and the express integration should be automatically enabled and hooked in when it's present.
No further intervention should be needed.

**Comment by smeubank** [comment]
> I would argue that this behavior should be the case for each platform where this is possible.
it is this way in python because python allows for detection at run time. In other platforms this is attempted via build tool plugins

see android bytecode manipulation with [gradle plugin](https://github.com/getsentry/sentry-android-gradle-plugin), issue in backlog to get this for Java too https://github.com/getsentry/sentry-android-gradle-plugin/issues/503

@AbhiPrasad to confirm but I don't think it is possibly a run time in node

**Comment by AbhiPrasad** [comment]
We removed the default auto-discovery in Node because it had a high runtime cost, up to 50% slower startup times for node. Also auto-discovery only works well for `cjs`, and since most people are now moving toward `esm` some setups don't work at all.

We now have a function that does this, `autoDiscoverNodePerformanceMonitoringIntegrations`. This is default included in all of our docs/onboarding snippets, but users can remove this if they don't want the performance hit.

```ts
const Sentry = require("@sentry/node");

Sentry.init({
  dsn: "

https://8308099df418455f9845cb7719b70590@o172566.ingest.sentry.io/1870657",
  integrations: [
    // enable HTTP calls tracing
    new Sentry.Integrations.Http({ tracing: true }),
    // Automatically instrument Node.js libraries and frameworks
    ...Sentry.autoDiscoverNodePerformanceMonitoringIntegrations(),
  ],

  // We recommend adjusting this value in production, or using tracesSampler
  // for finer control
  tracesSampleRate: 1.0,
});
```

**Comment by danielkhan** [comment]
> it is this way in python because python allows for detection at run time. In other platforms this is attempted via build tool plugins

Also possible for Node. You can wrap the module loader and intercept any loading of a module.

**Comment by AbhiPrasad** [comment]
> In non-serverless environments, startup time is not a metric we should overrotate on if it stays within bounds. In this case, I'd assume we are talking about 200ms vs 300ms.

The issue here is that `@sentry/node` is used not just for web server use cases, but in serverless, desktop (electron) and CLI use cases as well, where this cost can be substantial. In addition, adding more auto-discovered integrations would increasingly add to startup time since the cost comes from trying to dynamically require packages to see if they are being used. So as we added support for more frameworks, the cost kept increasing.

A better solution is to eventually create specific packages like `@sentry/express` and `@sentry/fastify` which have better defaults built in. We could also think about something like `@sentry/node-server`, but then we have to educate to make sure people understand to use `@sentry/serverless` if need be.

> Is esm really a thing for third-party Node modules? To my knowledge their immutability is always a problem.
How does this change when we discover them automatically? In addition, given that the majority of modules are still cjs, couldn't we still support them by only wrapping the ones where it's possible?

The issue isn't with the immutable nature of esm or even the actual module layout, it's with dynamic imports, which are needed so we can check if package exist. Checking `package.json` is not good enough in certain cases.

> Sentry.autodisover() was too short :) ?

Yeah we thought about this, but the name being super explicit turned out to be very easy for users to understand (and also see the benefit). Also people are only importing and and calling this function once, so not that bad a cost to pay.

**Comment by AbhiPrasad** [comment]
The best solution is actually to use [esm loaders](https://nodejs.org/api/esm.html#loaders), but this api is experimental and subject to change unfortunately.

**Comment by danielkhan** [comment]
@AbhiPrasad and I connected synchronously and had a few ideas. Will discuss this on a separate issue.
