### ISSUE TITLE
AioHttpIntegration not honoring capture_graphql_errors=False

### ISSUE THREAD

**Issue by Fwang36** [getsentry/sentry-python#2288]
### How do you use Sentry?

Sentry Saas (sentry.io)

### Version

1.29.0

### Steps to Reproduce

Reported by a user.  

The AioHttpIntegration is still capturing graphql errors even when capture_graphql_errors is set to false.

This is how the integration is being added -

```
integrations = []
integrations.append(AioHttpIntegration(capture_graphql_errors=False))

sentry_sdk.init(
  dsn=""
  integrations=integrations
)
```

### Expected Result

SentryGraphQLClientError errors should stop coming in.

### Actual Result

SentryGraphQLClientError errors are still being captured.

**Comment by sentrivana** [comment]
@Fwang36 Thanks for relaying -- we've removed the graphql integration in 1.29.2 and will rework it, so an update to 1.29.2 and removing the `capture_graphql_errors=False` option should fix the issue.

**Comment by andylamp** [comment]
I was the one who raised the issue with internal support - if getting help here is faster is better then I will do so in the future. It seems the support engineer just raised an issue template here with what I described.

Generally @sentrivana it is an extremely bad practice to enable a feature that can potentially affect quota/billing by default as it can lead to unexpected results. In our case, we burned a significant chunk of our error quota due to this...!

Thanks for the swift remedy though.

**Comment by sentrivana** [comment]
> I was the one who raised the issue with internal support - if getting help here is faster then I will do so in the future as my first step. It seems the support engineer just raised an issue template here with what I described.
> 
> Generally @sentrivana it is an extremely bad practice to enable a feature that can potentially affect quota/billing by default as it can lead to unexpected results. In our case, we burned a significant chunk of our error quota due to this...!
> 
> Thanks for the swift remedy though.

Hey @andylamp, that's definitely a valid point, the feature should have been opt-in by default.
