### ISSUE TITLE
Support upcoming version of RQ

### ISSUE THREAD

**Issue by selwin** [getsentry/sentry-python#2310]
### Problem Statement

I'm [RQ](https://github.com/rq/rq)'s maintainer and I use Sentry in production. I plan on releasing a major improvement to RQ sometime in the next few weeks, but this upcoming change breaks Sentry's integration.

### Solution Brainstorm

This [pull request](https://github.com/rq/rq/pull/1964) introduces a change that causes Sentry's RQ integration to fail. From what I can tell, the failure is caused by [this change](https://github.com/rq/rq/pull/1964/commits/fadbb233d81c5c1a53bfcae7149b80888c1e7bdd).

Can we get Sentry to support this change prior to the next major release of RQ? I plan on releasing this sometime in the next few weeks.

**Comment by sentrivana** [comment]
Hey @selwin, thanks a lot for the heads up! We'll have to see if someone has time to squeeze this in this week, because if not, realistically speaking it's not likely that we will be able to look at this until after next week.

**Comment by selwin** [comment]
Thanks @sentrivana !

**Comment by antonpirker** [comment]
Hey @selwin !

Comming week we have our Sentry interal hackweek. (Where we stop our day to day work, and hack on other stuff)
So we will pick up the RQ issue again in the week of August 28th. Don't know when exactly we can work on this, because we have still other things in our pipeline that need finishing first.

When exactly is your release planned?

**Comment by selwin** [comment]
Hi @antonpirker, no worries. My schedule is currently quite packed so the next release will probably be a month or two from now. Plenty of time still :)

**Comment by antonpirker** [comment]
Related: https://github.com/getsentry/sentry-python/issues/2363

**Comment by antonpirker** [comment]
Hey @selwin !
The `executions` branch of RQ is the one I should test with, right? Just double checking. All the other branches do not seem to be as new as this one.

**Comment by selwin** [comment]
> The executions branch of RQ is the one I should test with, right? Just double checking. All the other branches do not seem to be as new as this one.

That's correct, thanks :).

**Comment by vagi8** [comment]
Hey I was taking a look at this issue and working for a fix. 

@selwin  my understanding of the problem -  because of reversing the order of calling _handle_exception_ and _handle_job_failure_, this will raise an exception without setting the _job.set_status(JobStatus.FAILED,pipeline)_. does that make sense ?

**Comment by selwin** [comment]
@vagi8 thanks for investigating. If all it takes to make it work again is simply setting `job._status` to `FAILED`, this is something I can fix on my end. Can you point me to the block of code where `job.status` is cheked?

**Comment by antonpirker** [comment]
I think I know now what the problem is.

The function `handle_exception` is the one that Sentry patches to capture errors. In there we check `job.is_failed`: https://github.com/getsentry/sentry-python/blob/master/sentry_sdk/integrations/rq.py#L98

And only if `job.is_failed=True` then we capture an exception (and set `last_event_id` that you check in your tests)

But `is_failed` is set in `handle_job_failure` that you want to call after `handle_exception`.
So for Sentry the job looks perfectly fine and it does not capture any exception.

Why do you want to call `handle_exception` now before `handle_job_failure`?

**Comment by selwin** [comment]
> Why do you want to call handle_exception now before handle_job_failure?

One of the operations performed in `worker.handle_job_failure()` is removing the job from `StartedJobRegistry`, which is used to monitor which jobs are still running. `worker.handle_exception` runs user supplied exception handlers, which could take a while to run.

With the current (master branch) sequence of operations , if `worker.handle_exception()` runs for a long time, we won't be able to see that the job is actually still running.

If all you need is a flag indicating that a job has failed, I can set `job._status` to Failed so you know that an error has happened. How does that sound?

FYI, a major feature introduced in this branch is job `Execution`, which allows a single job to have multiple concurrent executions so the way to detect errors may also change.

**Comment by selwin** [comment]
> If all you need is a flag indicating that a job has failed, I can set job._status to Failed so you know that an error has happened. How does that sound?

If this sounds good, I can push an update on this branch so you can test your code against the updated branch.

**Comment by antonpirker** [comment]
> > If all you need is a flag indicating that a job has failed, I can set job._status to Failed so you know that an error has happened. How does that sound?
> 
> If this sounds good, I can push an update on this branch so you can test your code against the updated branch.

yes, please!

**Comment by selwin** [comment]
@antonpirker done! 

https://github.com/rq/rq/pull/1964/commits/dccfd979c2192828213241ab5d92050a35f15ff7

**Comment by antonpirker** [comment]
Thanks @selwin !

In theory it works now, but I discovered a strange behavior. Calling `job.is_failed` in the Sentry integration, changes the status of the job.

Look at this:
```
test_sentry.py > /Users/antonpirker/code/sentry-python/sentry_sdk/integrations/rq.py(100)sentry_patched_handle_exception()
     99             import ipdb; ipdb.set_trace()
--> 100             if job._status == JobStatus.FAILED or job.is_failed:
    101                 _capture_exception(exc_info)  # type: ignore

ipdb> job._status
<JobStatus.FAILED: 'failed'>
ipdb> job.is_failed
False
ipdb> job._status
'started'
ipdb> ```

So `job._status` is failed, but when I then call `job.is_failed` the `_status` is set to `'started'` because the `is_failed` gets the status from the connection and sets `_status`.

The `if` in the Sentry SDK works with the new behavior and I am also ok with releasing it like this (will add a note that the order of the `or` statement in the `if` is important. 

I just wanted to let you know about this behavior.

**Comment by selwin** [comment]
Thanks!

> So job._status is failed, but when I then call job.is_failed the _status is set to 'started' because the is_failed gets the status from the connection and sets _status.

Yes, `job.is_failed()` calls `get_status()` gets job status from Redis so the user gets the most recent status and caches it in `_status`. In hindsight I should have designed it a bit differently.

**Comment by antonpirker** [comment]
Support for the upcoming RQ version has been deployed @selwin : https://github.com/getsentry/sentry-python/releases/tag/1.32.0
So we are ready for you :-)

**Comment by selwin** [comment]
Thanks! Now the pressure is on me to finish the feature 😁
