### ISSUE TITLE
Does this library work with Sentry (server) >= 8 ?

### ISSUE THREAD

**Issue by pumazi** [getsentry/sentry-python#234]
**Will this package work with Sentry [server] >= 8?** I can't find anything in the docs to suggest it will, but then again, I don't see anything that says it does.

**Comment by untitaker** [comment]
I don't think we have a real policy around that. You will encounter a lot of "errors while processing event" due to unknown attributes even with Sentry 9 (related to https://forum.sentry.io/t/when-will-a-new-version-be-tagged-for-sentry-open-source/5622) and we don't make any guarantees, but it should be usable.
