### ISSUE TITLE
Transport causes CPU Spikes on Larger Envelopes

### ISSUE THREAD

**Issue by mitsuhiko** [getsentry/sentry-python#2384]
### How do you use Sentry?

Sentry Saas (sentry.io)

### Version

1.31

### Steps to Reproduce

Sending this to Sentry causes the transport to create CPU spikes that are very visible in our kubernetes pods.

```python
from sentry_sdk import capture_message, push_scope

for _ in range(50):
    with push_scope() as scope:
        scope.add_attachment(bytes=b"Hello World! " * 10000, filename="attachment.txt")
        capture_message('Hello, hello.')
```

It also happens if gzip compression is disabled. It appears to be related to how `capture_envelope` works within the transport.

### Expected Result

I would not expect the CPU usage to spike.

### Actual Result

It spikes.

**Comment by sl0thentr0py** [comment]
possible urllib3 stuff
https://github.com/psf/requests/issues/1910

**Comment by antonpirker** [comment]
I did some profiling today: (because sending is done in a worker thread, I profiled them on my local machine because in sentry we sould have not enough samples)

a) send 10 envelopes with big attachments (10000 hello worlds):
https://sentry-sdks.sentry.io/profiling/profile/sentry-python/6b7fc1ca0e30427cbf9d76ff2e1998dd/flamegraph/

![10_10000](https://github.com/getsentry/sentry-python/assets/202325/14ed7698-ab33-4516-a63e-960ce977f4c6)

b) send 50 envelopes with big attachments (10000 hello worlds):
https://sentry-sdks.sentry.io/profiling/profile/sentry-python/d446df68dd324870a5d0fb416a29e29b/flamegraph/
![50_10000](https://github.com/getsentry/sentry-python/assets/202325/b44aadb6-bec2-40dd-a11d-503a95858190)

c) send 50 envelopes with small attachments (10 hello worlds):
https://sentry-sdks.sentry.io/profiling/profile/sentry-python/ac9a8a1ae4f648a582ce375fe6e1e474/flamegraph/

![50_10](https://github.com/getsentry/sentry-python/assets/202325/a0e989ed-9e82-4ee7-973a-0ac02e9e3cff)


So there is nothing that jumps out. Most of the time is spent in the http lib (which was kind of our guess). I tried to disable SSL certificate verification, but this made not difference at all. 

One thing of not is that sending 10 envelopes takes around 350ms and sending 50 envelopes takes 2500ms (no matter what size the attachments) So that is not linear growth there.

We could create an AsyncHttpTransport (swapping out urllib3 with aiohttp) to see if the result changes drastically. But this is not done in a day.

**Comment by antonpirker** [comment]
Another note. I also tracked the cpu utilization of my test process. It maxed out at between 54% (10 small envelopes) 56% (10 large envelopes), and 61% (50 large envelopes). So I could not reproduce a cup utilization spike.

**Comment by antonpirker** [comment]
Another thing of notice: OpenSSL 3 has performance problems: https://github.com/python/cpython/issues/95031
Our server still has OpenSSL 1.1.1 so we are not affected, but when we update, we will. (and other customers might use OpenSSL 3 and are affected by those performance problems)
