### ISSUE TITLE
Make sure everything works with Django-Rest-Framework

### ISSUE THREAD

**Issue by untitaker** [getsentry/sentry-python#24]
We should django-rest-framework's `request.data` instead of trying to extract a structured body ourselves

**Comment by Skorpyon** [comment]
```
RawPostDataException
You cannot access body after reading from request's data stream```

Way how you read request body kill Django-Stripe integration

https://github.com/dj-stripe/dj-stripe/blob/3eafe287ac93d94f2615ff8a5b53ddf7e5e9e46c/djstripe/models/webhooks.py#L81

**Comment by untitaker** [comment]
I'm sorry, I can't reproduce this issue. Could you open a new issue, with a traceback?

**Comment by cwmoo740** [comment]
It's somewhat difficult to understand why using sentry with django_rest_framework does not upload request bodies out of the box. There were a few scattered SO and github threads about the problem but the few that I found refer to the older sentry client. I managed to track down the problem and wanted to share my results.

1. DRF uses its own json parser and calls request.read directly, without storing the result on django's request._body
2. Sentry attempts to read from django's request.body, which then errors because the stream has already been read and not assigned to request._body

Here are relevant parts of the code that I found:

https://github.com/encode/django-rest-framework/blob/3.9.0/rest_framework/parsers.py#L68

https://github.com/django/django/blob/2.1.5/django/http/request.py#L283

One workaround is to do something silly like this:

```
@api_view(['POST'])
def my_view(request):
    request.body # side effect of storing the whole request body in memory
    do_something(request.data)
```

I put up a repo demonstrating this. 

https://github.com/cwmoo740/django_sentry_debugging

It would be significantly better imo if there was a separate integration for DjangoRestFramework that simply read from request.data directly and let DRF do the parsing.

**Comment by Anton-Baton** [comment]
Hi, I've also faced this issue when using DRF 3.9.0 and sentry-sdk 0.7.8 (0.7.4 also has this). With new unified sdk request bodies aren't sent to Sentry UI. 

I was able to track it down to the place where issue occurs.

When extracting data from request, sdk tries to get body [here](https://github.com/getsentry/sentry-python/blob/master/sentry_sdk/integrations/_wsgi_common.py#L97), but it's impossible due to the `You cannot access body after reading from request's data stream` error. It is raised when sdk is trying to read `self.request.body` inside the called function in [django integration](https://github.com/getsentry/sentry-python/blob/master/sentry_sdk/integrations/django/__init__.py#L255).

**Comment by untitaker** [comment]
@cwmoo740 I'm very sorry I dropped the ball on this. Your investigation is very complete and I will fix this in the next release.

**Comment by untitaker** [comment]
0.7.10 was released which should fix this

**Comment by Audiopolis** [comment]
This is happening on 2.0.1
