### ISSUE TITLE
Using defined span creation on static class method cause TypeError

### ISSUE THREAD

**Issue by GeorgeS1995** [getsentry/sentry-python#2525]
### How do you use Sentry?

Sentry Saas (sentry.io)

### Version

1.35.0

### Steps to Reproduce

Deps:
fastapi==0.87.0

Steps to reproduce
- Create class with static method and signature like that:
```@dataclass
class SentryTracedService:
    @staticmethod
    def f4(a = None):
        return a
```
- Create any route that call this method with argument
```
@app.get("/")
def r():
    sts = SentryTracedService()
    sts.f4(1)
    return {"Hello": "World"}
```
- Add to sentry init this method
```
    sentry_sdk.init(
        ...
        functions_to_trace=[{"qualified_name": "path_to_cls.SentryTracedService.f4"}],
    )
```
- Call route with this static method

### Expected Result

The route runs back properly without any errors caused by the static method. Additionally, tracing of this method is added to the performance tab.

### Actual Result

Got a error:
TypeError: SentryTracedService.f4() takes from 0 to 1 positional arguments but 2 were given

**Comment by sentrivana** [comment]
Hey @GeorgeS1995, thanks for the report and clear steps to repro! That will make it easier for us to debug.

**Comment by szokeasaurusrex** [comment]
Hey @GeorgeS1995, I am currently trying to figure out how we can fix this bug. While investigating the bug, I discovered a workaround you can use until a fix is released.

Specifically, you will need to use the [`sentry_sdk.trace`](https://docs.sentry.io/platforms/python/performance/instrumentation/custom-instrumentation/#using-a-decorator-1) decorator to mark the static method for tracing, instead of using `functions_to_trace` in the `sentry_init` method. When using the `sentry_sdk.trace` decorator, you will also need to ensure it is placed **after** the `staticmethod` decorator. So, your example would need to be modified like so:

```python
import sentry_sdk

class SentryTracedService:
    @staticmethod
    @sentry_sdk.trace
    def f4(a = None):
        return a

...

sentry_sdk.init(
    ... # Remove SentryTracedService.f4 entry from functions_to_trace
)
```

Hope this helps!
