### ISSUE TITLE
[trytond] Drop support for Trytond<6.0.0

### ISSUE THREAD

**Issue by n1ngu** [getsentry/sentry-python#2653]
### Problem Statement

Support for old 5.0.X LTS series ceased on November 2023. Previous versions weren't even LTS and are plain legacy.

### Solution Brainstorm

Most of the Tryton community won't be interested in any trytond<6.0.0 support, so just drop it on sentry-sdk 2.0!

This is also an opportunity to drop back-compatibility boilerplate for trytond<5.4 error handlers and simplify the tox dependency matrix due to modern werkzeug incompatibility in old trytond versions.

**Comment by n1ngu** [comment]
See 
- https://github.com/getsentry/sentry-python/pull/2652#discussion_r1455887468
- https://github.com/getsentry/sentry-python/pull/2652#discussion_r1455884823

**Comment by n1ngu** [comment]
Tryton release process spec: https://discuss.tryton.org/t/release-process/395

**Comment by sentrivana** [comment]
Hey @n1ngu, thanks for bringing this up. In general we try to support even legacy versions of libraries/frameworks/Python itself for as long as it makes sense (you've probably noticed we still support Python 2.7, for instance). There obviously comes a point where it stops making sense because the ecosystem has largely moved on -- we'll evaluate if this applies to (at least some) old Trytond versions.

**Comment by szokeasaurusrex** [comment]
Closing because we decided to support [Triton 4.6+](https://docs.sentry.io/platforms/python/integrations/tryton/#supported-versions) in version 2.0 of the SDK.

**Comment by n1ngu** [comment]
Curious: is the decision based on actual usage by Sentry users in that Tryton series that also keep their SDK updated?
