### ISSUE TITLE
Questions: PasteDeploy and setting tags

### ISSUE THREAD

**Issue by AvnerCohen** [getsentry/sentry-python#274]
Couldn't find the relevant documentation.

https://docs.sentry.io/clients/python/integrations/pyramid/#pastedeploy-filter

What would be the equivalent of this configuration in versus raven-python:
```
[pipeline:main]
pipeline =
 raven
 tm
 MyApp

[filter:raven]
use = egg:raven#raven
dsn = https://aa:aaa@sentry.io/aaa
include_paths = my.package, my.other.package
exclude_paths = my.package.crud
```

Also, what would be the way to add custom tags to to be sent with exception? for instance the "environment" ?

**Comment by untitaker** [comment]
All the old PasteDeploy integration did was to wrap the WSGI middleware around your app. You can achieve the same thing with https://docs.sentry.io/platforms/python/wsgi/. We might bring [the filter](https://github.com/getsentry/raven-python/blob/d891c20f0f930153f508e9d698d9de42e910face/raven/contrib/paste.py) back, but then not in a way that allows you to set client options from your PasteDeploy config, because we wanted to unify this by forcing everything through `init` or `Client`.

As for the second part of your question, please refer to https://docs.sentry.io/enriching-error-data/context/?platform=python. You can call `configure_scope` at import time as well as in a request handler. Tags set at import time will survive the request while tags set in the request handler will be cleared at the end of a request.

**Comment by untitaker** [comment]
I hope this answers the question. I created #275 for tracking demand for a PasteDeploy filter. However, I think given that this is very little code that we don't need it, just better docs.
