### ISSUE TITLE
Async monitor decorator makes type checking complex

### ISSUE THREAD

**Issue by kojiromike** [getsentry/sentry-python#2939]
### How do you use Sentry?

Sentry Saas (sentry.io)

### Version

1.44.1

### Steps to Reproduce

1. Create two simple synchronous functions that returns a type, where one is decorated and the second calls the first:

```
from sentry_sdk.crons.decorator import monitor

@monitor(monitor_slug="test")
def foo() -> int:
    return 1

def bar() -> int:
    return foo()
```

2. Run mypy on both and see if the behavior is the same in v1.44.0 and v1.44.1

### Expected Result

The functions are synchronous and there is no type failure in v1.44.1. 

### Actual Result

When testing upgrading to 1.44.1, we got a type failure from mypy that was not there using the 1.44.0 sdk version. Our function returns a dictionary, not an `int`, but the essentials are the same as above.

We see

```
Incompatible return value type (got "dict[str, list[dict[str, Any]]] | Awaitable[dict[str, list[dict[str, Any]]]]", expected "dict[str, list[dict[str, Any]]]") [return-value]
```

But since our function is synchronous, mypy should not be confused by the `Awaitable`. I think this is ultimately due to `inspect.iscoroutinefunction` being a runtime check that mypy does not use for type elimination.

**Comment by szokeasaurusrex** [comment]
@kojiromike This indeed appears to be because of how we typed the monitor after the `async` changes.

The problem is that we have [defined the `monitor` to return `Callable[P, Union[R, Awaitable[R]]]`](https://github.com/getsentry/sentry-python/blob/669ed17d95bb6fd53025bf520ecb025dd48cb8bc/sentry_sdk/crons/_decorator.py#L21). We instead need to add overloads to specify that `monitor` returns `Callable[P, R]` when it is passed a `Callable[P, R]`, and that it returns `Callable[P, Awaitable[R]]` when it receives a `Callable[P, Awaitable[R]]`.

I will work on a fix now. Hopefully, we will have it ready soon!

**Comment by kojiromike** [comment]
NB this appears to be very similar to the situation reported https://github.com/python/mypy/issues/15520, and largely handled in https://peps.python.org/pep-0742/.
