### ISSUE TITLE
Metrics not sent on program exit

### ISSUE THREAD

**Issue by szokeasaurusrex** [getsentry/sentry-python#2983]
### How do you use Sentry?

Sentry Saas (sentry.io)

### Version

1.45.0 and 2.0.0rcX

### Steps to Reproduce

Follow [these steps](https://github.com/szokeasaurusrex/issue-reproductions/tree/main/getsentry/sentry-python/2983).

### Expected Result

The `drank-drinks` metric is sent to Sentry, regardless of whether we call `sentry_sdk.flush()` before the program's end.

### Actual Result

The `drank-drinks` method is only sent if we call `sentry_sdk.flush()` before the program ends, or if we interrupt the program by pressing `⌃C`. If we run the code with `sentry_sdk.flush()` commented out, i.e. without modifying the sample in "Steps to Reproduce," the metric does not get sent.

**Comment by szokeasaurusrex** [comment]
Possibly related: #687

**Comment by sentrivana** [comment]
This is because in Python 3.12 you can't start a new thread at interpreter shutdown. If you just let the program finish, the atexit hook will try to get the transport to send the pending events, but since the transport worker doesn't have a thread running yet, it first has to try to start one -- which fails [here](https://github.com/getsentry/sentry-python/blob/d9d87998029fb0ef2bfe933cea0b69bfee60ed51/sentry_sdk/worker.py#L71). If you `Ctrl+C` the program in between, the thread gets started before the atexit hook, which is fine.

We can look into improving this but I'm not sure how likely this is to happen in real world usage. Usually the worker thread has already been set up so there's no need to start it at shutdown. We _could_ probably start it right away instead of on demand, but that could lead to issues on setups that fork the process the SDK is running in.

**Comment by szokeasaurusrex** [comment]
Closing due to [planned changes](https://sentry.zendesk.com/hc/en-us/articles/26369339769883-Upcoming-API-Changes-to-Metrics) to metrics API, which will likely make this bug irrelevant
