### ISSUE TITLE
Profiling not working

### ISSUE THREAD

**Issue by ShuaiShao93** [getsentry/sentry-python#3026]
### How do you use Sentry?

Sentry Saas (sentry.io)

### Version

1.45.0

### Steps to Reproduce

1. initialize sentry globally, enable profiling
2. Add this block to a function. Note that `self.execute_model` is implemented in a subclass
3. 
<img width="688" alt="image" src="https://github.com/getsentry/sentry-python/assets/7556010/19b2e38e-2e3c-4a2e-af55-4e6a09f01f23">
4. wait for profiling to show up on sentry.io

### Expected Result

Full profile for self.execute_model

### Actual Result

<img width="1680" alt="image" src="https://github.com/getsentry/sentry-python/assets/7556010/e7e1724c-78b2-49ed-8312-24af7e3d414f">

**Comment by ShuaiShao93** [comment]
Adding a child span in self.execute_model seems to work, but I'm not sure this is intended

**Comment by szokeasaurusrex** [comment]
Hi @ShuaiShao93, I need some more information to understand your issue.

From the screenshots you provided, it looks like profiling is working as it is supposed to. Can you please explain exactly what is wrong?

If possible, assuming you are using SaaS (sentry.io), could you please also share a link to the profile in Sentry?

**Comment by ShuaiShao93** [comment]
@szokeasaurusrex I can see more details after adding a nested span, like 
<img width="1501" alt="image" src="https://github.com/getsentry/sentry-python/assets/7556010/ba7a6343-0172-4892-a7fc-83cd43c3dfa8">

But from the documentation of profiling, I didn't see anything about span.

**Comment by szokeasaurusrex** [comment]
> @szokeasaurusrex I can see more details after adding a nested span, like <img alt="image" width="1496" src="https://private-user-images.githubusercontent.com/7556010/326502229-ed73f27b-6add-4650-beca-190bf70eed71.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ0MDY4NDMsIm5iZiI6MTcxNDQwNjU0MywicGF0aCI6Ii83NTU2MDEwLzMyNjUwMjIyOS1lZDczZjI3Yi02YWRkLTQ2NTAtYmVjYS0xOTBiZjcwZWVkNzEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQyOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MjlUMTYwMjIzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OGI3MGEzMmIwYWEyYmVkZTZjZGU4ODQ0YzJlMTJjN2ZmMTc3Y2MwOWI1YzlkZDU0MTBkNjEwMWMyZGU3YzYxNCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.uOkzKoHSzP1Pfnv593JFE9rGqGKm_USsmkpyVZNquac">
> 
> But from the documentation of profiling, I didn't see anything about span.

@ShuaiShao93 If I understand correctly, your problem is that the profile is missing some stack frames when you don't start a nested span. Is that right?

If that is correct, I also have a few more questions:
  - Can you please provide the code you ran to make this profile? I would like to see how you added the nested span
  - Can you please provide a link to this profile, and also a link to the profile from your initial comment?

**Comment by szokeasaurusrex** [comment]
@ShuaiShao93 I think the reason you see a difference between the two profiles is because the [more detailed one](https://run-galileo.sentry.io/profiling/profile/wizard-dev/dc2c17341e3e491c80eb975adff601e1/flamegraph/?colorCoding=by+system+vs+application+frame&query=&sorting=call+order&tid=140109495070720&view=top+down) has a duration of just over 1 second, while the [less detailed profile](https://run-galileo.sentry.io/profiling/profile/wizard-dev/1e6ab752a47a47718803cd9fa6e93750/flamegraph/?colorCoding=by+system+vs+application+frame&query=&sorting=call+order&tid=140198303551488&view=top+down) has a duration of only approximately 14 milliseconds. The difference in detail between the two profiles can most likely be explained by the Python profiler's design.

Specifically, the Python profiler is a sampling profiler, which means that instead of capturing the start and end of every function call, we simply sample the call stack at regular intervals. Our sampling rate is approximately 100 samples/second, so the Python profiler is only accurate to approximately 10 milliseconds. Any function calls that are shorter than 10 milliseconds, and which occur between taking two samples, would not show up in the profile. Since the less detailed profile lasts only 14 milliseconds, we only would expect to have at most two samples, so the level of detail we see in the profile is expected.

___________

The one thing that confuses me, however, is that the profile from the original screenshot seems to have taken longer than 1 second. The 10 millisecond profiler accuracy does not explain this result, so we likely still have a problem here. Could you please share a link to a longer profile where you are missing detail?

**Comment by ShuaiShao93** [comment]
Thanks for the explanation! @szokeasaurusrex 

Originally I thought it was because of the span, now after checking more profiles, I believe it was because the function call was too short, so whether it could catch the trace is actually random. Next time we will only profile longer functions.
