### ISSUE TITLE
Django integration: You cannot access body after reading from request's data stream

### ISSUE THREAD

**Issue by Audiopolis** [getsentry/sentry-python#3045]
### How do you use Sentry?

Sentry Saas (sentry.io)

### Version

2.0.1

### Steps to Reproduce

Environment info:
django=5.0.4
djangorestframework=3.15.1

1. Add sentry integration to django app:

```python3
if ENV != "development":
    sentry_sdk.init(
        dsn="https://....ingest.sentry.io/6010199",
        integrations=[
            DjangoIntegration(
                transaction_style="url",
                middleware_spans=True,
                signals_spans=True,
                cache_spans=False,
            )
        ],
        debug=DEBUG,  # This is true in this case
        send_default_pii=True,
        environment=ENV,
    )
```

2. `logger.exception("This is an exception")
3. See traceback

### Expected Result

Either the exception is successfully logged to Sentry, or it's not sent to Sentry at all since it's a log entry and not an unhandled exception.

### Actual Result

```
# Traceback for the `logger.exception` call goes here

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/sentry_sdk/integrations/django/__init__.py", line 555, in parsed_body
    return self.request.data
           ^^^^^^^^^^^^^^^^^
AttributeError: 'ASGIRequest' object has no attribute 'data'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/sentry_sdk/integrations/django/asgi.py", line 56, in asgi_request_event_processor
    DjangoRequestExtractor(request).extract_into_event(event)
  File "/usr/local/lib/python3.12/site-packages/sentry_sdk/integrations/_wsgi_common.py", line 96, in extract_into_event
    parsed_body = self.parsed_body()
                  ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/sentry_sdk/integrations/django/__init__.py", line 557, in parsed_body
    return RequestExtractor.parsed_body(self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/sentry_sdk/integrations/_wsgi_common.py", line 142, in parsed_body
    return self.json()
           ^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/sentry_sdk/integrations/_wsgi_common.py", line 154, in json
    raw_data = self.raw_data()
               ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/sentry_sdk/integrations/django/__init__.py", line 538, in raw_data
    return self.request.body
           ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/http/request.py", line 328, in body
    raise RawPostDataException(
django.http.request.RawPostDataException: You cannot access body after reading from request's data stream
```

**Comment by szokeasaurusrex** [comment]
Hi @Audiopolis, I attempted to reproduce your issue using [this code](https://github.com/szokeasaurusrex/issue-reproductions/tree/main/getsentry/sentry-python/3045), but I did not observe the error message that you reported.

Can you please clarify how exactly you encountered this issue? If possible, please share a reproduction with me (you can also do so by opening a PR on my [reproduction repo](https://github.com/szokeasaurusrex/issue-reproductions/tree/main/getsentry/sentry-python/3045) and sharing a link to the PR here).

**Comment by Audiopolis** [comment]
@szokeasaurusrex Thanks for trying. I will try to create a reproduction. In the meantime, I'll clarify how I encountered the issue:

We send an email from a Django view using Resend. In this environment, Resend does not recognize the domain, so it throws an error. We catch that error and use `logger.exception(...)` instead, where `logger = logging.getLogger(__name__)`. The view returns a 201 response. Then, the exact traceback I added to this issue description is printed.

The original request is automatically converted from an `ASGIRequest` (no `data` attribute, and can only read body once) to a RES framework `Request` (has a cached `data` property) by REST framework. I don't know how Sentry gets the original ASGIRequest instead of the DRF Request, but since it does, it makes sense that `'ASGIRequest' object has no attribute 'data'` and `You cannot access body after reading from request's data stream`. I will have to analyze the situation more closely and provide a reproduction.

**Comment by antonpirker** [comment]
Same error is also happening inside Sentry with SDK 2.1.1: 
```
  File "/usr/local/lib/python3.11/site-packages/sentry_sdk/integrations/django/__init__.py", line 555, in parsed_body
    return self.request.data
           ^^^^^^^^^^^^^^^^^
AttributeError: 'WSGIRequest' object has no attribute 'data'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/sentry_sdk/integrations/django/__init__.py", line 486, in wsgi_request_event_processor
    DjangoRequestExtractor(request).extract_into_event(event)
  File "/usr/local/lib/python3.11/site-packages/sentry_sdk/integrations/_wsgi_common.py", line 96, in extract_into_event
    parsed_body = self.parsed_body()
                  ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sentry_sdk/integrations/django/__init__.py", line 557, in parsed_body
    return RequestExtractor.parsed_body(self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sentry_sdk/integrations/_wsgi_common.py", line 142, in parsed_body
    return self.json()
           ^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sentry_sdk/integrations/_wsgi_common.py", line 154, in json
    raw_data = self.raw_data()
               ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sentry_sdk/integrations/django/__init__.py", line 538, in raw_data
    return self.request.body
           ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/http/request.py", line 328, in body
    raise RawPostDataException(
django.http.request.RawPostDataException: You cannot access body after reading from request's data stream", "level":"error", "name":"sentry_sdk.errors"}
```
Can be seen here: https://cloudlogging.app.goo.gl/yfAdqBdmA8iER8ZQ8 (retricted link)

**Comment by sentrivana** [comment]
So just to expand on what was already written here, the way DRF works is that it wraps the native Django [`WSGIRequest`](https://github.com/django/django/blob/a09082a9bec18f8e3ee8c10d473013ec67ffe93b/django/core/handlers/wsgi.py#L56) (or `ASGIRequest`) in its own [`Request`](https://github.com/encode/django-rest-framework/blob/36d5c0e74f562cbe3055f0d20818bd48d3c32359/rest_framework/request.py#L140). The wrapper class adds some stuff on top and proxies everything else to the underlying Django request.

We capture the data [here](https://github.com/getsentry/sentry-python/blob/40746ef9dad676c8cc704a1fb955b93047c06b93/sentry_sdk/integrations/django/__init__.py#L552). Basically, `self.request.data` is only expected to be there if this is a DRF `Request`; otherwise we essentially fall back to `self.request.body` (that's what `RequestExtractor.parsed_body(self)` eventually looks at). Reading the `body` on a Django request should be fine but in some cases the body has already started being read and we hit [this](https://github.com/django/django/blob/a09082a9bec18f8e3ee8c10d473013ec67ffe93b/django/http/request.py#L328-L330).

The quick "fix" would be to capture `RawPostDataException` when we try to access `request.body` and just give up on reading the body ourselves and return `None`. However this doesn't address the underlying problem of why `request.data` is not there in the first place (it indeed looks like we're working with the Django request instead of the DRF one).

Wasn't able to repro this yet -- @Audiopolis What does the request look like in your app? I assume it's a POST? Does it contain any form data, uploaded files, etc.? Do you access anything on the request in the view?
