### ISSUE TITLE
Sentry can't be initialized twice

### ISSUE THREAD

**Issue by nirga** [getsentry/sentry-python#3059]
### How do you use Sentry?

Sentry Saas (sentry.io)

### Version

1.45.0

### Steps to Reproduce

We have a library where we use sentry internally to track exceptions. A customer of ours installed our library and they also use sentry. Our exceptions are being reported to both his Sentry account and ours.

### Expected Result

There should be an option to isolate the exceptions

### Actual Result

Our exception is shown on the other Sentry account

**Comment by szokeasaurusrex** [comment]
Hi @nirga, unfortunately this use case is unsupported – the Sentry SDK is only designed to monitor end-user applications, not libraries.

Due to the Sentry SDK's fundamental design, the SDK can only be initialized once during the application lifecycle. Initializing the SDK multiple times, as you have attempted to do by using Sentry in your library, leads to undefined behavior, like what you have observed with events being sent both to your Sentry and the customer's Sentry. This undefined behavior occurs because upon initialization, the SDK hooks into the libraries we integrate with and other application lifecycle events (such as an unhandled exception being raised). If the SDK has been initialized twice, we will hook into everything again, and the two initializations will interact in undefined ways.

Even the simpler use case of sending Sentry events to two different DSNs within a single application – when the Sentry SDK is only being initialized once in the user code – is difficult to solve nicely. For that use case, users [can have two separate Sentry hubs](https://github.com/getsentry/sentry-python/discussions/1521) for each DSN, and they can manually select which hub to send events to by using a `with hub` context manager. However, using two separate hubs likely fails to solve your use case, since your library would need to somehow detect whether the user code is using Sentry, and only initialize Sentry in the library when the user code does not use Sentry.

Since the Sentry Python SDK is not designed for monitoring libraries, we unfortunately will need to close this issue. You could attempt some kind of workaround based on the multi-hub setup I mentioned earlier, but since your use case is unsupported, we cannot assist with any difficulties you may face if you chose to pursue this option.

Thank you in advance for your understanding; if you have any questions, please let us know!

**Comment by smeubank** [comment]
hi @nirga !

Thanks for writing in.

> We have a library where we use sentry internally to track exceptions. A customer of ours installed our library and they also use sentry. Our exceptions are being reported to both his Sentry account and ours.

Generally I agree with everything @szokeasaurusrex wrote above, but I'd like to better understand what you want to achieve and the setup of the libraries you mentioned.

So in this case, you are describing an internal library which wraps Sentry, and some logic to monitor https://github.com/traceloop/openllmetry for your internal usage? So you import your `sentry_library` along side `traceloop-sdk`? This is running in the wild to report telemetry of errors? 

Or is this part of `traceloop-sdk` under the hood?

**Comment by nirga** [comment]
Thanks @smeubank! I wonder if [what I've done here](https://github.com/traceloop/openllmetry/blob/main/packages/traceloop-sdk/traceloop/sdk/telemetry.py) is what you meant?
