### ISSUE TITLE
DJANGO - Sentry does not work in production, only in development environments

### ISSUE THREAD

**Issue by luisgs7** [getsentry/sentry-python#3065]
### How do you use Sentry?

Sentry Saas (sentry.io)

### Version

2.1.1

### Steps to Reproduce

In the local development environment, using Docker, all data is tracked to sentry, however when the same project is run in a production environment, it does not work.

The current infrastructure consists of Linux servers, Ubuntu 22.04, and the entire application runs in a docker container. It consists of a Django API, using Django version 4.0.10.

With debug activated in production, these are the logs presented:
![Captura de tela de 2024-05-10 21-12-50](https://github.com/getsentry/sentry-python/assets/54151493/4fd84f72-2c01-4fbc-9055-898eb2f402eb)
![Captura de tela de 2024-05-10 21-12-59](https://github.com/getsentry/sentry-python/assets/54151493/499eec51-06c0-4377-bed2-2179ff4bc87b)

### Expected Result

The production code is this:

```python
sentry_sdk.init(
    dsn=os.environ.get("SENTRY_DNS"),
    integrations=[DjangoIntegration()],
    traces_sample_rate=1.0,
    send_default_pii=True,
)
```

And django debugging is disabled in production.

### Actual Result

Thank you in advance for your help.

**Comment by szokeasaurusrex** [comment]
@luisgs7 I will need you to provide more information about your exact setup in order to be able to help you.

What is different between your development and production environments? How can you tell that Sentry is working in production, but not in development? 

The one thing I can see is that in your initialization code snippet, you are setting `dsn=os.environ.get("SENTRY_DNS")`. Perhaps, you mean to set `dsn=os.environ.get("SENTRY_DSN")`?
