### ISSUE TITLE
Work pool

### ISSUE THREAD

**Issue by SEKIRO-J** [getsentry/sentry-python#312]
I'm using sentry on top of tornado.
I notice that in old sdk (raven), the action of sending http request to sentry server is a coroutine that could be put in tornado.ioloop.
However, in the new sdk, the implementation is using multi-threading to send request.

Is this a intended design?
I'm concerning that multi-threading is heavier than coroutine when do context-switch.

**Comment by untitaker** [comment]
@SEKIRO-J We wanted to avoid making the SDK depend on the code that it monitors (if tornado crashes before the ioloop starts, the old SDK will not send any data), and also because one implementation of the transport is easier to debug and maintain than multiple. The assumption is that the average application does not send so many errors.

We're not 100% convinced by this decision but it was a conscious one.

**Comment by untitaker** [comment]
To clarify, if this slows down your application performance it's unacceptable.

**Comment by SEKIRO-J** [comment]
Thanks, that explains my questions.

**Comment by untitaker** [comment]
That's great to hear!
