### ISSUE TITLE
Deprecate and reduce instrumenter usage internally

### ISSUE THREAD

**Issue by sl0thentr0py** [getsentry/sentry-python#3151]
Unclear currently how this is going to work in a backwards compat way

**Comment by szokeasaurusrex** [comment]
@sl0thentr0py, I think it is okay for us to drop `instrumenter` without deprecating it first and without making the change backwards compatible, since we already [document](https://getsentry.github.io/sentry-python/api.html#sentry_sdk.api.start_transaction) `instrumenter` as being "for internal use only."

Ideally, we would remove the `instrumenter` in the Phase 1 major release; however, I would argue that since `instrumenter` is explicitly mentioned as being for internal use, we can safely remove it even in a minor version.

**Comment by sl0thentr0py** [comment]
We cannot remove the top level option though if someone is setting it in their `init` since that's breaking. We can remove all internal references but the init options has to be deprecated and stay till the major. 
That being said, we will probably do a major anyway so let's see.

**Comment by szokeasaurusrex** [comment]
Fair enough @sl0thentr0py. Although, I would imagine that few, if any, users set a custom instrumenter in their `init`, since we don't seem to document this functionality anywhere, as far as I can tell (e.g., `instrumenter` is missing from [this page](https://docs.sentry.io/platforms/python/configuration/options/)). 

Worst case, I think we can get away with emitting a `DeprecationWarning` when `instrumenter` is set and otherwise ignoring the parameter's value (perhaps technically breaking, but it at least won't break people's apps).

**Comment by sl0thentr0py** [comment]
it is required while using our span processor so far and is documented here
https://docs.sentry.io/platforms/python/tracing/instrumentation/opentelemetry/#usage

side note: while searching for docs usages, it is better as a dev to grep for a keyword in the docs repo rather than looking through the website to find something

**Comment by szokeasaurusrex** [comment]
We have decided to split this task as follows: 

 - Clarifying that `instrumenter` parameters (except to `init`) are internal-only (#3299)
 - Fully deprecating `instrumenter` option (https://github.com/getsentry/sentry-python/pull/3308), to be merged in last 2.x version
 - Removing the `instrumenter` option in the POTel base branch

**Comment by szokeasaurusrex** [comment]
Closing in favor of #3320 and #3321.
