### ISSUE TITLE
Strawberry Integration - Tracing Does Not Appear to Work

### ISSUE THREAD

**Issue by keithhackbarth** [getsentry/sentry-python#3285]
### How do you use Sentry?

Sentry Saas (sentry.io)

### Version

2.9.0

### Steps to Reproduce

1. Install the Strawberry Quick Start https://github.com/strawberry-graphql/strawberry
2. Install the Sentry Strawberry Plugin
3. Log in to Sentry

### Expected Result

Strawberry transactions should show in the Sentry Performance panel.

### Actual Result

Strawberry transactions do _not_ show in the Sentry Performance panel.

**Comment by keithhackbarth** [comment]
What a solution could look like here:

```
class Schema(strawberry.Schema):
    async def execute(
        self,
        query: str,
        variable_values: dict[str, Any] | None = None,
        context_value: Any | None = None,
        root_value: Any | None = None,
        operation_name: str | None = None,
        *args,
        **kwargs,
    ):
        with sentry_sdk.start_transaction(op="gql", name=operation_name):
            return await super().execute(
                query,
                *args,
                variable_values=variable_values,
                context_value=context_value,
                root_value=root_value,
                operation_name=operation_name,
                **kwargs,
            )

    async def subscribe(
        self,
        query: str,
        variable_values: dict[str, Any] | None = None,
        context_value: Any | None = None,
        root_value: Any | None = None,
        operation_name: str | None = None,
        *args,
        **kwargs,
    ):
        with sentry_sdk.start_transaction(op="gql", name=operation_name):
            return await super().subscribe(
                query,
                *args,
                variable_values=variable_values,
                context_value=context_value,
                root_value=root_value,
                operation_name=operation_name,
                **kwargs,
            )

 ```

**Comment by patrick91** [comment]
From the Strawberry side, happy to make changes to make this easy to implement if it is not already 😊

**Comment by szokeasaurusrex** [comment]
@keithhackbarth What server framework are you using when serving your Strawberry API? We would expect the Sentry integration for the server to create the transactions – you would see Strawberry spans in the trace view under the server framework's transactions.

**Comment by keithhackbarth** [comment]
Hi @szokeasaurusrex,

I'm hoping to get some clarity on something. From my understanding, the server framework wouldn't have any context about the transaction name, right? It seems like the GraphQL transaction name is only available at the GraphQL layer, and the Sentry "Performance" tab only supports reporting at the transaction level. Because of this, spans are only helpful if the transaction is thoughtfully done; otherwise, you would see 100% of transactions grouped into a single unhelpful transaction (see screenshot).
<img width="825" alt="Screenshot 2024-07-15 at 10 05 36 AM" src="https://github.com/user-attachments/assets/c973a46e-e882-4d0e-a82c-64a5415cd250">

That is the key differentiator between GraphQL and REST. I've noticed that other popular Python GraphQL libraries like Graphene or Strawberry use Sentry transactions for this purpose. Is there something I might be missing? Have you personally had success with performance monitoring using Strawberry on a real project?

@patrick91, I'd really appreciate your input as well. I tried the code snippet recommended by the community, but unfortunately, it didn’t work for me. Any insights you could share would be incredibly helpful and would love a PR if you think you have visibility on the issue.

Thank you both so much!

**Comment by szokeasaurusrex** [comment]
@keithhackbarth Hmm yes indeed. I think what you are seeing is the expected behavior at the moment. The transaction name is set in the server framework, and to see what Strawberry is doing, you would need to look at the spans. 

But I can see your point that having everything grouped under the single endpoint limits the Strawberry integration's usefulness, and we should probably look into whether we can improve this behavior somehow. 

If I remember correctly, @sentrivana worked on creating the Strawberry integration, so maybe she would have an idea about how we can improve this or why we chose this design

**Comment by sentrivana** [comment]
@keithhackbarth Thanks for opening the issue, this is great feedback!

The usual pattern is that the ASGI/WSGI server creates the transaction and whatever library or framework is running on the server then creates spans under that transaction. I think this general approach still works here, we're just missing one important piece, which is overriding the default transaction name you get from the web framework integration so that calls to the `/graphql` endpoint are not considered one event, but rather are grouped under a specific operation name.

I'll whip something up.

**Comment by keithhackbarth** [comment]
@sentrivana - Thank you so much. I confirmed its working great! You are our hero 🦸 

<img width="942" alt="Screenshot 2024-07-16 at 12 07 03 PM" src="https://github.com/user-attachments/assets/efd58c05-f008-4102-be0a-e092a5f9642d">

**Comment by sentrivana** [comment]
@keithhackbarth Awesome, thanks for trying it out and reporting back! <3
