### ISSUE TITLE
How do we make sure coroutine safe in sentry?

### ISSUE THREAD

**Issue by SEKIRO-J** [getsentry/sentry-python#333]
I'm using sentry on top of tornado, unfortunately I couldn't use the tornado integration because neither my python version nor my tornado version satisfied.

Now I'm concerning about coroutine safety, for example, 
routine A push_scope, with tags infoA, yield
routine B push_scope, with tags infoB, yield
routine A proceeds, report exception, wrong tags info will be sent.

How do we solve this problem? I've read a similar issue in  https://github.com/getsentry/sentry-python/issues/147
The solution gives in that post doesn't seem to help ```with Hub(hub.current)```

**Comment by untitaker** [comment]
We haven't spent any time on supporting async frameworks that don't support contextvars, because as far as I know it works differently for each async framework. This is the only reason for the strict version requirements of the Tornado integration.

I think something like this could work: https://gist.github.com/simon-weber/7755289 But instead of setting and resetting a `thread.local()`, you set and reset `Hub.current` (which already uses a `thread.local()` anyway). We can build this into the integration and support more Tornado versions as a result. I would certainly merge a PR that implements this.

Let me know if you have any questions.

**Comment by antonpirker** [comment]
As this issue is very old and it seems there is no demand for this, I will close this issue.

If you come along this issue and want to improve support for Tornado, please create another issue and link to this one. Thanks!
