### ISSUE TITLE
feat: sentry-dramatiq integration

### ISSUE THREAD

**Issue by jacobsvante** [getsentry/sentry-python#3387]
### Problem Statement

5 years ago I created [sentry-dramatiq](https://github.com/jacobsvante/sentry-dramatiq) and there seems to be some active users. I am no longer maintaining the library as I no use Python.

### Solution Brainstorm

Would you consider integrating it into sentry-sdk or perhaps taking over the maintenance of the project?

**Comment by sentrivana** [comment]
Hey @jacobsvante, first of all thank you for your work on the integration and for maintaining it. We'd be happy to make this part of the SDK.

How would you prefer we go about this? Will you open a PR against `sentry-python` or should we take care of everything? (I'd prefer the former so that you get proper credit in commit history, but up to you.)

**Comment by jacobsvante** [comment]
Thank you for the swift response and for your willingness to integrate it! As I no longer work with Python I think it'd be best if you add the actual code. I don't mind being without credit 😊

**Comment by jacobsvante** [comment]
@antonpirker sounds good!

**Comment by antonpirker** [comment]
@jacobsvante the dramatic integration has been released in Python SDK version 2.13.0:
https://github.com/getsentry/sentry-python/releases/tag/2.13.0

Thanks again for the great work and the donation of your code!

**Comment by jacobsvante** [comment]
This is great news. Thanks for integrating it!

**Comment by pencil** [comment]
@jacobsvante As a user of `sentry-dramatiq`, thank you for maintaining the library for the past years – and for finding a new maintainer 🙌
