### ISSUE TITLE
2.15.0: Test test_redis_disabled_when_not_installed failing when packaging for openSUSE

### ISSUE THREAD

**Issue by kastl-ars** [getsentry/sentry-python#3624]
Dear maintainers,

I tried to update the openSUSE package for sentry-sdk, but one of the tests fails in the new version 2.15.0.

```
[  155s] =================================== FAILURES ===================================
[  155s] ____________________ test_redis_disabled_when_not_installed ____________________
[  155s] tests/test_basics.py:894: in test_redis_disabled_when_not_installed
[  155s]     assert sentry_sdk.get_client().get_integration(RedisIntegration) is None
[  155s] E   assert <sentry_sdk.integrations.redis.RedisIntegration object at 0xffff87f892a0> is None
[  155s] E    +  where <sentry_sdk.integrations.redis.RedisIntegration object at 0xffff87f892a0> = get_integration(RedisIntegration)
[  155s] E    +    where get_integration = <sentry_sdk.client._Client object at 0xffff90da0250>.get_integration
[  155s] E    +      where <sentry_sdk.client._Client object at 0xffff90da0250> = <function get_client at 0xffffa027f250>()
[  155s] E    +        where <function get_client at 0xffffa027f250> = sentry_sdk.get_client
[  155s] =============================== warnings summary ===============================
```

Any idea where to start looking, why this fails?

Kind Regards,
Johannes

**Comment by sentrivana** [comment]
Hi @kastl-ars, thanks for packaging the SDK.

The test case is supposed to check that the Redis integration doesn't get auto-enabled if Redis is not detected in installed packages. To make this reproducible we're simulating an ImportError being thrown on `import redis`, but it seems something's not working as expected.

How are you running the test suite? Is this the only test that's failing? There's a similar test that uses the same mechanism (`test_auto_enabling_integrations_catches_import_error`), is that one successful?

If I can repro this I'd try to fix the test case, but honestly I think we could also just get rid of it since `test_auto_enabling_integrations_catches_import_error` tests the same thing in a more general way.

**Comment by sentrivana** [comment]
Removed the test -- will be out in 2.16.0 either today or tomorrow.
