### ISSUE TITLE
Specify loggers for sentry handler

### ISSUE THREAD

**Issue by Ashish-Bansal** [getsentry/sentry-python#365]
Hello everyone!

We recently replaced raven with new sentry-sdk. Raven was configured through standard library's logging module configuration. We were specifying the loggers to which sentry's handler would be attached. So, sentry used to post messages from our specified loggers and all other uncaught exceptions through `sys.excepthook`.

In sentry-sdk, I can't find any such option. So, we are using `before_send` in the new sdk.

```
def before_send(event, hint):
    logger = event.get('logger')
    if logger and logger not in specific_loggers:
        return None
    return event
```

Is it the correct way to do things in the new sdk ?

Thanks!

**Comment by untitaker** [comment]
That's a fine way to do it. On https://docs.sentry.io/platforms/python/logging/ you will find references to two `logging.Handlers` that you can register explicitly too instead of using the logging integration. This is useful if your logging setup is very complex and you want to make the new system work similarly to Raven. But I think `before_send` is quite good for this.

Does this help?

**Comment by Ashish-Bansal** [comment]
I see. Thanks for the help!
