### ISSUE TITLE
Test assumes system timezone is UTC

### ISSUE THREAD

**Issue by szokeasaurusrex** [getsentry/sentry-python#3720]
[This test](https://github.com/getsentry/sentry-python/blob/02d09346e6d070e03b828807d72485b6f23b2c11/tests/test_utils.py#L70-L73), added in https://github.com/getsentry/sentry-python/issues/3546, assumes that the system time is UTC. The test fails otherwise because Python interprets the timestamp as if it is using the system's local timezone, but we assert that it is interpreted in UTC.

**Comment by BYK** [comment]
@szokeasaurusrex thanks for the report! Can you share which Python version this occurs on as I was not on UTC when I was writing this test and the point of the test was to make sure it worked on non-UTC timezone settings.

I'm assuming the culprit is us [trying `fromisoformat()` first](https://github.com/getsentry/sentry-python/pull/3546/files#diff-e9f88ca6368ce622839e078ed26c741a927752c01ceae64cd504d3ae86de6fd2R248) which defaults to local timezone when there's no timezone set.

**Comment by szokeasaurusrex** [comment]
@BYK I think it was 3.12
