### ISSUE TITLE
When we pinned pip==24.0 in python, Installing sentry-sdk[django,pure_eval]==2.18.0 doesn't install pure_eval dependencies

### ISSUE THREAD

**Issue by JayDarjiAubergine** [getsentry/sentry-python#3754]
### How do you use Sentry?

Sentry Saas (sentry.io)

### Version

2.18.0

### Steps to Reproduce

When I create fresh virtualenv from `python 3.9` and install `sentry-sdk[django,pure_eval]==2.18.0` then it correctly install its pure_eval dependencies which are `asttokens`, `executing` and `pure_eval`

Notice that here by default pip version is `24.2`

![Image](https://github.com/user-attachments/assets/7601d354-dcbf-475b-ab6e-0316c81941f0)

---
Now, when we manually pin pip version to `24.0` which we need for our other dependencies to work, it's not installing pure_eval dependencies at all!

Notice that here we have one warning which was not there in the previous one where we had pip > 24.0! 

pure_eval dependencies are: https://github.com/getsentry/sentry-python/blob/2.18.0/setup.py#L73

Warning was:
> WARNING: sentry-sdk 2.18.0 does not provide the extra 'pure-eval'

![Image](https://github.com/user-attachments/assets/613d6f1e-5d8f-458c-88c6-8a25bf7c93df)

And now check the dependencies, which don't have  `asttokens`, `executing` and `pure_eval` at all

![Image](https://github.com/user-attachments/assets/55a788ec-0911-4ce6-8545-04859edcb6b4)

---

Is it a problem from sentry-sdk or is it something problematic with pip itself?
The workaround I used for now is to manually pinned those 3 dependencies in my requirements.txt file as of now, but that's not good.
Help will be appreciated.

### Expected Result

The expected installation would be to install those dependencies automatically when we specify it in installation without depending on pip version.

### Actual Result

Installed without specified dependencies which we can see above in the Summary section.

**Comment by sentrivana** [comment]
Hey @JayDarjiAubergine, thanks for the great bug report! Made it very easy to reproduce this. The problem is the `pure_eval` extra alone (i.e., even if you don't add the `django` extra into the mix and just try to install `sentry-sdk[pure_eval]`, it'll fail).

This is indeed a pip issue. It's there in 24.0 and gone in 24.1. [This issue](https://github.com/pypa/pip/issues/12688) specifically looks like the source of the problem.

We can do something on the SDK side though to make it installable in 24.0 too. I'll take care of that. In the meantime, if you need to work around this, there's a couple of options:
- Using `pip==24.1` (or newer). You write that 24.2 doesn't work with your setup, but maybe 24.1 still would?
- Adding the extra requirements manually, as you did
- Patching your `sentry-sdk`'s `setup.py`'s `extras_require` so that 
  ```python
  "pure-eval": ["pure_eval", "executing", "asttokens"],
  ```
  becomes
  ```python
  "pure_eval": ["pure_eval", "executing", "asttokens"],
  ```
  The underscore/dash situation is what pip is having issues with -- this is what we'll do SDK-side to fix this.

**Comment by JayDarjiAubergine** [comment]
Thanks, @sentrivana for the reply and quick fix.

Just a quick question with the fix that you've created:

Currently we are installing `sentry` with `pure_eval`  like this `sentry-sdk[django,pure_eval]==2.18.0`

After that fix has been released, is it advisable to change to `sentry-sdk[django,pure-eval]==2.18.0`
Notice the underscore changed to a hyphen here.

I know that you told in the PR that 

> (The underscore version sentry-sdk[pure_eval] will continue to work after this change.)

But, will it be removed at a later stage and only a hyphen will be supported?

What is the recommended Sentry way to install `pure_eval`? With an underscore or with a hyphen?

Also, can you let us know when can we expect this fix to be released?

**Comment by JayDarjiAubergine** [comment]
Thanks for the detailed reply @sentrivana! Appreciated.

> But please verify once the release is out.

Sure. I can verify this here once it is released.

**Comment by sentrivana** [comment]
Hey @JayDarjiAubergine, 2.19.0 is now out, let me know if you can get the `pure_eval` extra to work, either with underscore or hyphen.

**Comment by JayDarjiAubergine** [comment]
Hey @sentrivana, thanks for the release update.

Yes, `pure_eval` is working now with an underscore and hyphen both. Thanks.
