### ISSUE TITLE
SystemExit and KeyboardInterrupt no longer caught (regression from raven-python)

### ISSUE THREAD

**Issue by saifelse** [getsentry/sentry-python#379]
The same reasoning as getsentry/raven-python#675 applies for sentry-python,
where gunicorn raising a SytemExit(1) is something we would like to capture
in Sentry, as it is unexpected behavior from the application.

**Comment by WhyNotHugo** [comment]
Huh, I've the opposite issue: raven did not log this, but the new client does.
However, I don't want this logged, since it doesn't make sense to me (the system will exit on every deployment, and that can happen way too many times).

Is there any way to avoid logging `SystemExit`? It doesn't make sense to me, and is filling my sentry issues board.

**Comment by untitaker** [comment]
@WhyNotHugo can you confirm those events have the wsgi mechanism?

**Comment by WhyNotHugo** [comment]
Yes, they all do.

**Comment by untitaker** [comment]
Hmm, from what I know this means you abort gunicorn while it is handling a request and that might be the wrong way to shut it down.

In any case you can explicitly ignore this error like any error class with this here: https://github.com/getsentry/sentry-python/issues/149#issuecomment-434448781

**Comment by WhyNotHugo** [comment]
Hmmm... let me double check, I believe we're killing gunicorn gracefully, but I might be wrong.

**Comment by WhyNotHugo** [comment]
Yeah, looks like docker was killing them before gunicorn's internal grace period, I'll tweak that and it should solve it for me. Thanks.
