### ISSUE TITLE
Exception: raise OSError("handle is closed")

### ISSUE THREAD

**Issue by GuangTianLi** [getsentry/sentry-python#423]
When I initialized sentry_sdk and used concurrent.futures.process.ProcessPoolExecutor, the exception will be raised after python exit.

```
from concurrent.futures.process import ProcessPoolExecutor

import sentry_sdk

sentry_sdk.init(dsn="")


def test():
    ...


if __name__ == "__main__":
    with ProcessPoolExecutor(max_workers=4) as worker:
        worker.submit(test)
```

The exception:
```
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/Users/tony.li/miniconda3/lib/python3.7/concurrent/futures/process.py", line 101, in _python_exit
    thread_wakeup.wakeup()
  File "/Users/tony.li/miniconda3/lib/python3.7/concurrent/futures/process.py", line 89, in wakeup
    self._writer.send_bytes(b"")
  File "/Users/tony.li/miniconda3/lib/python3.7/multiprocessing/connection.py", line 183, in send_bytes
    self._check_closed()
  File "/Users/tony.li/miniconda3/lib/python3.7/multiprocessing/connection.py", line 136, in _check_closed
    raise OSError("handle is closed")
OSError: handle is closed
```

**Comment by untitaker** [comment]
Thanks for the report, I can reproduce this but have no idea what is happening.

**Comment by GuangTianLi** [comment]
The reason caused this problem is very interesting and I proposed a solution to fix it.  But I think it is a little trick, I think it is great if there is any more elegance way to resolve it.

**Comment by bjorns** [comment]
I got this error when a function ran sys.exit(1) on a critical error. Because ProcessPoolExecutor creates new full processes, those processes gets exited instead of the parent process which just keeps running and fails on cleanup instead. To fix, try replacing ProcessPoolExecutor with a ThreadPoolExecutor and see where the process exits. Then replace sys.exit with an exception that can be caught and handled properly.
