### ISSUE TITLE
Sentry for Spark on Databricks

### ISSUE THREAD

**Issue by kutny** [getsentry/sentry-python#568]
Hi,

I wonder how to correctly integrate Sentry with **Databricks** https://databricks.com/ (Spark as a Service from the Spark founders).

I've spent some time trying to integrate Sentry with the Databricks IPython-base shell, but still not sure if it works correctly. I was not able to integrate SparkWorkerIntegration to the Spark worker nodes and also the Spark Streaming errors are not caught to Sentry...

Has anyone any experience with the Databricks integration?

Thanks

**Comment by untitaker** [comment]
cc @AbhiPrasad

**Comment by AbhiPrasad** [comment]
Hey thanks for reaching out @kutny.

We've done some early testing with Databricks when we initially developed the Spark integration. 

Can you provide some more details on your cluster setup? What Spark Config and client libraries (python packages) does the cluster use? Also, are you running an initialization script of any kind?

I'm also interested in hearing about your use case with Databricks in more detail. Do you mind reaching out to me at aprasad@sentry.io so we can chat about it?

**Comment by kutny** [comment]
Hi @AbhiPrasad, sure! We use the newest Databricks Runtime (DBR) 6.1 with Python 3 only for both batch processing and streaming.

As described in [your documentation](https://blog.sentry.io/2019/11/12/sentry-for-data-error-monitoring-with-pyspark), I tried to initialize Sentry before creating the SparkContext/SparkSession. I found it pretty challenging as when I initialized Sentry in the first cell of the Databricks notebook, it is already too late as SparkSession is AFAIK initialized before the initialization of the notebook environment.

So I tried to monkey-patch the /dbfs/tmp/[random-timestamp]/PythonShell.py library, which handles the SparkSession initialization by adding the following code at the very beginning of the PythonShell.py file:

```
import os, sys, subprocess
subprocess.run([sys.executable, '-m', 'pip', 'install', 'sentry-databricks'], check=True)
from sentry_databricks.notebook import initSentry
initSentry(os.environ['SENTRY_DSN'], os.environ['APP_ENV'], [os.environ['APP_ROOT_NAMESPACE']])
```

As you can see I have created the [sentry-databricks python package](https://pypi.org/project/sentry-databricks/) to simplify the Sentry initialization from Databricks.

After some testing, it works well even with the SparkWorkerIntegration enabled, see my Databricks config:
![image](https://user-images.githubusercontent.com/729373/69704327-78eb3800-10f3-11ea-9ab6-92b33691bcce.png)

My monkey-patching solution is very hackish so I hope that you would give me a better one :-)

Still, Sentry is not able to catch some types of errors, mostly in the Spark Streaming jobs:

![image](https://user-images.githubusercontent.com/729373/69704737-5574bd00-10f4-11ea-93bc-0516f14853d2.png)

We use PySpark so in Spark streaming, we **cannot** use the following code to catch the streaming exceptions:

![image](https://user-images.githubusercontent.com/729373/69705039-fc595900-10f4-11ea-9c4d-b2a9936184dd.png)

In PySpark, StreamingQuery.awaitTermination() blocks the current thread. I found out, in such case, only the first initiated stream in notebook is processed, others wait as awaitTermination() blocks further processing. In Java/Scala I would probably use the onQueryTerminated() listener method of the StreamingQueryListener() instead to catch streaming exceptions. However, that approach is [not available in PySpark ](https://spark.apache.org/docs/latest/structured-streaming-programming-guide.html#reporting-metrics-programmatically-using-asynchronous-apis).

I have found a very hackish solution on SO which somehow adds the events listeners to PySpark, not sure if it will work https://stackoverflow.com/questions/47357418/how-to-get-the-output-from-console-streaming-sink-in-zeppelin#answer-47487443

Thanks for your support!

**Comment by AbhiPrasad** [comment]
Hey, thank you for the detailed reply, helped a lot! Sorry on the delay with this, it's Thanksgiving holiday here in the US.

In terms of your monkey patching, that is probably an easy fix. We can check in our integration if an existing `SparkSession/SparkContext` exists and patch it. That way you can easily just call `Sentry.init` even with the `SparkSession ` already being initialized. I will write up a patch for this.

Alright the `StreamingQueryListener` is a little more problematic for us (as you mentioned it's not avaliable in PySpark). There are a couple of options we have here. 

First, we could adjust the integration to use Py4J and get the streaming query event listener using Scala/Java <-> Python calls (in fact the integration uses `SparkListener` to generate breadcrumbs - https://github.com/getsentry/sentry-python/blob/master/sentry_sdk/integrations/spark/spark_driver.py#L205-L206). This is pretty much how the stackoverflow answer does it. Not the cleanest because it's not a first class PySpark API.

Second, and what I think will be easier for you, is to use https://github.com/getsentry/sentry-spark#sentrystreamingquerylistener-spark-sql, as part of our new ScalaSpark Sentry integration.

You will have to install the [maven dependency on your cluster](https://docs.databricks.com/libraries.html#maven-libraries) - `io.sentry:sentry-spark_2.11:0.0.1-alpha04`

You can then use the Spark Config option `spark.sql.streaming.streamingQueryListeners`: `io.sentry.spark.listener. SentryStreamingQueryListener`.

Again, appreciate all your help with this! Please let me know if you have any other questions.

**Comment by kutny** [comment]
Thanks @AbhiPrasad, unfortunately, the installation of your maven package prevents the DBX cluster from starting:
![image](https://user-images.githubusercontent.com/729373/69790209-58d67a00-11c2-11ea-8c90-3cfc02bf7549.png)

**Comment by kutny** [comment]
Log4j:

Caused by: java.lang.ClassNotFoundException: io.sentry.spark.listener.SentryStreamingQueryListener

Detailed trace attached
[sentry_databricks_error.txt](https://github.com/getsentry/sentry-python/files/3900678/sentry_databricks_error.txt)

**Comment by kutny** [comment]
![image](https://user-images.githubusercontent.com/729373/69790794-6fc99c00-11c3-11ea-8610-301cf818c30b.png)
![image](https://user-images.githubusercontent.com/729373/69790897-a0a9d100-11c3-11ea-890a-aa36b5c708a5.png)

**Comment by AbhiPrasad** [comment]
Hey, just wanted to give you an update.

Very strange that you are getting class not found exceptions, I pushed up an example demo with the listener and it seems to be working fine https://github.com/sentry-demos/apache-spark/blob/master/scala-spark-example/src/main/scala/SimpleStreamingQueryApp.scala#L14. Not sure why it's not working on Databricks. Maybe the JAR can only be accessed by Scala Jobs for some reason?

An alternative then is to download the JAR from https://mvnrepository.com/artifact/io.sentry/sentry-spark_2.11/0.0.1-alpha04, and [upload it to your cluster](https://docs.databricks.com/libraries.html#upload-a-jar-python-egg-or-python-wheel).

I'll also do some more investigation on my side into this.

Alright, as for the `PySpark` side of things, I have a patch for the `SparkContext` changes ready. The streaming query event listener is a little more complicated though. 

`StreamingQueryListener` is defined as an [abstract class](https://github.com/apache/spark/blob/master/sql/core/src/main/scala/org/apache/spark/sql/streaming/StreamingQueryListener.scala#L32) which means we can't use Py4J to use a Python Proxy.

https://www.py4j.org/advanced_topics.html#implementing-java-interfaces-from-python-callback

> Python classes can only implement Java interfaces. Abstract or concrete classes are not supported because Java does not natively support dynamic proxies for classes. Extending classes may be supported in future releases of Py4J.

This means that we have to use the method of adding a Scala subclass to access the methods like in the Stackoverflow link you posted above. This means that unfortunately until Spark adds the listener natively to pyspark, we can't support it Python side. 

For now I opened an issue on the Spark JIRA - https://issues.apache.org/jira/browse/SPARK-30105.

**Comment by kutny** [comment]
Hi @AbhiPrasad I tried again by downloading the JAR from the given maven link resulting in the same ClassNotFound error as before. Not sure what is wrong, but IMHO it does not have anything to do with PySpark as the Databricks/Spark cluster does not start at all after installing your package and adding the spark.sql.streaming.streamingQueryListeners io.sentry.spark.listener.SentryStreamingQueryListener Spark config option.

As of streaming: I understood that it **is possible** to catch errors in streaming jobs when Sentry is initialized before SparkContext initialization however It is **not possible** to catch errors in streaming jobs when using the new "late" SparkContext "on-the-fly patching" specifically developed for Databricks. Did I understand that correctly?

**Comment by kutny** [comment]
Have you read this [article on the Databricks website](https://databricks.com/blog/2017/05/18/taking-apache-sparks-structured-structured-streaming-to-production.html)? It contains some examples of using the _onQueryProgress_ and _onQueryTerminated_ listeners in Databricks...

**Comment by AbhiPrasad** [comment]
> Have you read this article on the Databricks website? It contains some examples of using the onQueryProgress and onQueryTerminated listeners in Databricks...

Not sure why it the `ClassNotFound` error is occurring. We follow the same approach as the article you cited to create `onQueryProgress` and `onQueryTerminated` listeners in the `sentry-spark` package - https://github.com/getsentry/sentry-spark/blob/master/src/main/scala/io/sentry/spark/listener/SentryStreamingQueryListener.scala#L8.

This might be something you have to ask Databricks support about, it might be that JARs are loaded differently if you are using PySpark notebooks instead of Scala notebooks, or there is some additional cluster configuration to use.

> As of streaming: I understood that it is possible to catch errors in streaming jobs when Sentry is initialized before SparkContext initialization however It is not possible to catch errors in streaming jobs when using the new "late" SparkContext "on-the-fly patching" specifically developed for Databricks. Did I understand that correctly?

Without the `StreamingQueryListener`, it will *not* be possible to catch errors in streaming jobs, we will encounter those thread issues you cited earlier with the current approach. This is true for both initing Sentry before SparkContext initialization and for the on-the-fly-patching. I am experimenting with some workarounds, specifically patching `awaitTermination()` directly, to see if we can solve this without the use of the listener.

**Comment by antonpirker** [comment]
There has been a lot of work already done here. Can @AbhiPrasad or @kutny just give a short update on the state of affairs. Is this something that can be finished and merged without lots of development time needed, or is this a bigger project and unclear how to get this done?
