### ISSUE TITLE
Why does Sentry recommend me to use aiohttp integration in my sanic app

### ISSUE THREAD

**Issue by wei-hai-pai** [getsentry/sentry-python#640]
I have an application using Sanic framework and I am using **SanicIntegration** to initiate Sentry, however, Sentry recommended me to use **aiohttp** integration. Why is that and should I use **aiohttp** integration to initiate Sentry? What's the diff or benefit from aiohttp integration?

This is how I initiate Sentry in the codebase

```
sentry_sdk.init(
            dsn=app.config["SENTRY_DSN"],
            environment=app.config["REALM"],
            integrations=[SanicIntegration()]
        )
```

<img width="638" alt="Screen Shot 2020-03-03 at 11 30 58 AM" src="https://user-images.githubusercontent.com/35832146/75812279-cc000700-5d42-11ea-880e-65b781e4bbb9.png">

**Comment by untitaker** [comment]
If you do not use aiohttp-server as web framework this integration is entirely useless. We only see that you have the `aiohttp` package installed in the virtualenv your app is running, and make assumptions based on that. Those suggestions are not always relevant.

These alerts are mostly targeted at people who install the Sentry SDK for their Django app, do not enable the Django integration (prob because they were not aware of it) and just live with the fact that their events are nearly useless.

There's no harm in enabling the integration though, in fact it's useful because it makes the alert go away :)

**Comment by wei-hai-pai** [comment]
@untitaker got it, `aiohttp` is a dep of package `elasticsearch_async` in my application and I think that's what triggers the recommendation. My question would be how do I enable `aiohttp` integration while I am using `SanicIntegration` already?

**Comment by untitaker** [comment]
Import both and write `integrations=[ SanicIntegration(), AiohttpIntegration() ]`

**Comment by wei-hai-pai** [comment]
@untitaker thank you!
