### ISSUE TITLE
Invalid HTTP_HOST header

### ISSUE THREAD

**Issue by discover59** [getsentry/sentry-python#641]
I used raven package in Django before and it worked well so far.
Recently I replaced it with latest sentry-python and getting weird error notifications continuously.

```
Invalid HTTP_HOST header: 'server_ip'. You may need to add 'server_ip' to ALLOWED_HOSTS.
```

I added server domain, 127.0.0.1 and localhost in allowed hosts.

I think there is no direct request to server IP instead of the domain.

Any help to fix the issue is appreciated.

**Comment by untitaker** [comment]
Where are you getting that error? In your project or when submitting events from the SDK to Sentry?

**Comment by discover59** [comment]
Sentry is integrated in my django project and the same event from the project pushed to sentry.
Sometimes it also produces events with `example.com` and `169.254.169.254` instead of `server_ip`.

**Comment by untitaker** [comment]
Could you link me the sentry issue that shows this error?

**Comment by discover59** [comment]
https://sentry.io/share/issue/8d076660ee2d4009b734d0d594ab0288/

**Comment by untitaker** [comment]
Yeah this came up a few times before. I think we should just start ignoring that logger, for now you can do:

```python
from sentry.integrations.logging import ignore_logger
ignore_logger("django.security.DisallowedHost")
```

**Comment by discover59** [comment]
Thanks.
But I cannot ignore all errors related to DisallowedHost.
I have to track some of those.
Not sure why there are example.com and other strange server ips.

**Comment by untitaker** [comment]
Because those errors happen. Somebody is sending this as Host header. I am not sure by which criteria you want to filter.

**Comment by discover59** [comment]
Is it possible to ignore errors with certain host headers in project?
I don't want such invalid errors to fill my sentry event count.

**Comment by untitaker** [comment]
Yes, you can use the [`before_send` option](https://docs.sentry.io/learn/filtering/?platform=python#before-send) to look at the event that is about to be sent and `return None` to throw the event away.

**Comment by discover59** [comment]
Ok, let me try. Thanks.

**Comment by untitaker** [comment]
Another option is to use the "message filters" option in the project settings.

**Comment by camilonova** [comment]
I'm having the same Issue.

@untitaker if i choose the "message filters" it will count at the sentry messages per month?

**Comment by untitaker** [comment]
@camilonova no, you will not be billed for those events

**Comment by discover59** [comment]
@camilonova It's better to resolve it on web server such as nginx or apache instead of ignoring such issues.

**Comment by camilonova** [comment]
I got this nginx configuration:

```
server {
    listen                      *:80 default_server deferred;

    server_name                 _ "";

    return                      444;
}
```

It is supposed to catch them but seems is not working. This issue started when migrated from raven to sentry-sdk.

@discover59 how did you do?

**Comment by pixelicous** [comment]
New to sentry, added it to django, configured everything and i was happy, until i had to waste a few hours on investigating what the hell is going on with these, why do i get example.com errors??
I do not remember including any "example.com" request in the code or in a script (even tried to find one)
Is there a possibility this is related to being on a shared cloud service such as AWS' ECS?

Could you provide an explanation of why this happens? Are these caused due to django nature, sentry bug?

Another example of error message
Invalid HTTP_HOST header: '169.254.169.254'
On /latest/dynamic/instance-identity/document

I am pushing a new nginx image to my repo to check @camilonova 's tip

**Comment by pixelicous** [comment]
wasted some hours on investigating what the hell is going on with these, i also get weird example.com errors
I do not remember including any "example.com" request in the code or in a script (even tried to find one)
Is there a possibility this is related to being on a shared cloud service such as AWS' ECS?

Could you provide an explanation of why this happens? Are these caused due to django nature, sentry bug?

Another example of error message
Invalid HTTP_HOST header: '169.254.169.254'
On /latest/dynamic/instance-identity/document

**Comment by untitaker** [comment]
"AWS Security Scanner", sounds like AWS employs a bot that is used to figure out if you're accepting random host headers. You're not, because you're using Django.

I wasn't aware of those types of scanners. The initial thought of reporting those types of messages to Sentry was that you'd catch broken configuration that way (requests from your own services with invalid host headers). I guess as long as it's easy enough to filter those events using either [before_send](https://docs.sentry.io/learn/filtering/?platform=python#before-send) or server-side message filters it's alright though.

Let me know your opinions.

**Comment by untitaker** [comment]
One thing we could do is to add AWS Security Scanners to our list of web crawlers that we offer a filter for: https://docs.sentry.io/accounts/quotas/#inbound-data-filters

**Comment by untitaker** [comment]
We decided not to swallow those errors but rather filter out false positive errors like AWS Security Scanner. see also https://github.com/getsentry/relay/pull/577

**Comment by pixelicous** [comment]
@untitaker im not the original issue creator, but thanks for this :)

**Comment by discover59** [comment]
Updated nginx configuration and it fixed this issue.
In addition to snippet in https://github.com/getsentry/sentry-python/issues/641#issuecomment-609054574, I had to add the configuration for 443 as well.

```
server {
    listen                      80 default_server;
    listen                      [::]:80 default_server;
    listen                      443 ssl default_server;
    ssl_certificate /etc/letsencrypt/live/example.com/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/example.com/privkey.pem; # managed by Certbot
    return                      444;
}
```

**Comment by rbtsolis** [comment]
```
from sentry_sdk.integrations.logging import ignore_logger

ignore_logger("django.security.DisallowedHost")
```

**Comment by jonholdsworth** [comment]
> Yeah this came up a few times before. I think we should just start ignoring that logger, for now you can do:
> 
> ```python
> from sentry.integrations.logging import ignore_logger
> ignore_logger("django.security.DisallowedHost")
> ```

All the above gives me the impression this is actually, 'literally', to do with Logging. Not message-sending.
I'll dig a bit deeper.
