### ISSUE TITLE
sentry_sdk.capture_exception has incomplete type annotation

### ISSUE THREAD

**Issue by elhawk** [getsentry/sentry-python#675]
When porting from raven to sentry_sdk, I ported a call to `capture_exception` passing an `ExcInfo` tuple.  This caused mypy to fail.  Looking at the code, 

`sentry_sdk.capture_exception` takes `error=None,  # type: Optional[BaseException]`, but then it passes directly to `hub.capture_exception` which has the type `# type: Optional[Union[BaseException, ExcInfo]]`, where `ExcInfo` maps to the tuple.

I have worked around this with a `# type: ignore`, but I think the type on `sentry_sdk.capture_exception` should be expanded to match `hub.capture_exception`.

**Comment by untitaker** [comment]
Thanks, can you prepare a PR for this?

**Comment by glyph** [comment]
Was this fixed in #702 ?

**Comment by glyph** [comment]
(i.e. was #682 a dup of this?)

**Comment by untitaker** [comment]
Hi glyph, yes it was actually fixed there. Please note, for anybody finding this issue: Generally we do not guarantee stable type annotations, i.e. changes in type annotations are not subject to semver. This is largely because

* each version of mypy fixes at least one bug that causes another error to pop up (which we can't possibly predict)
* there will always be one usage we break by replacing `Any` with a concrete type

In any case I'll close this issue now.

**Comment by untitaker** [comment]
and @glyph I do not believe #682 was a dupe, seems like I referenced the wrong issue there.

**Comment by glyph** [comment]
Thanks for the update @untitaker !
