### ISSUE TITLE
Support for Proxy Authentication

### ISSUE THREAD

**Issue by emenendez** [getsentry/sentry-python#676]
Hi there! Thanks for all you do with Sentry -- it adds incredible value to our team.

I have a question about support for HTTP proxy authentication in `sentry_sdk`.

**TL;DR:** Is proxy authentication supported? If not, can it be? Without support for proxy auth, we can't use Sentry from a significant portion of our services.

**More details:**

I see that we can pass a `https_proxy` kwarg to `sentry_sdk.init()`, such as:

```
sentry_sdk.init("https://...@foo.ingest.sentry.io/...", https_proxy="http://user:pass@proxy")
```

However, it looks like that proxy string eventually gets passed to `urllib3.ProxyManager()` here: https://github.com/getsentry/sentry-python/blob/0da369f839ee2c383659c91ea8858abcac04b869/sentry_sdk/transport.py#L293

Unfortunately, `urllib3.ProxyManager` does not appear to respect credentials passed in this string. The [documentation](https://urllib3.readthedocs.io/en/latest/reference/#urllib3.poolmanager.ProxyManager) isn't super clear on this, but it does allude to it in the description of the `proxy_headers` kwarg: "Could be used for proxy authentication." We verified with packet captures that `urllib3.ProxyManager` is not adding a `Proxy-Authorization` HTTP header to requests when the proxy string includes credentials.

Thanks so much for your consideration and help with this!

**Comment by marius56782** [comment]
You can solve it by subclassing the default `HttpTransport`. This is not a pretty solution since it overrides a method prefixed by `_` and it requires us to parse the proxy url twice. The best thing would be if the maintainers gave some pointers on how they want to solve the problem. Still, this way seems to work.
```
"""
Transport subclass which enables proxy authentication
"""
import urllib3

from sentry_sdk.transport import getproxies
from sentry_sdk.transport import HttpTransport


def add_proxy_auth_header(opts: dict, proxy: str):
    """Adds Proxy-Authorization to opts"""
    parsed_proxy = urllib3.util.url.parse_url(proxy)
    if parsed_proxy.auth:
        opts.setdefault("proxy_headers", {})
        auth_header = urllib3.util.make_headers(proxy_basic_auth=parsed_proxy.auth)
        opts["proxy_headers"].update(auth_header)


class ProxyAuthHttpTransport(HttpTransport):
    def _make_pool(
        self,
        parsed_dsn,  # type: Dsn
        http_proxy,  # type: Optional[str]
        https_proxy,  # type: Optional[str]
        ca_certs,  # type: Optional[Any]
    ):  # type: (...) -> Union[PoolManager, ProxyManager]
        proxy = None
        no_proxy = self._in_no_proxy(parsed_dsn)

        # try HTTPS first
        if parsed_dsn.scheme == "https" and (https_proxy != ""):
            proxy = https_proxy or (not no_proxy and getproxies().get("https"))

        # maybe fallback to HTTP proxy
        if not proxy and (http_proxy != ""):
            proxy = http_proxy or (not no_proxy and getproxies().get("http"))

        opts = self._get_pool_options(ca_certs)

        if proxy:
            add_proxy_auth_header(opts, proxy)

        if proxy:
            return urllib3.ProxyManager(proxy, **opts)
        else:
            return urllib3.PoolManager(**opts)
```

**Comment by antonpirker** [comment]
I will put this in our internal low priority list. We will do some proper road map planning in the next couple of weeks and look at all the enhancements (also this one) and decide if and when we will do them.

**Comment by sl0thentr0py** [comment]
picking this up,
we will just add another top level config `proxy_headers` that will passthroughed to `ProxyManager`

**Comment by keimlink** [comment]
Thank you for implementing this! 🙏🏼

I'm working in a team at one of Sentry's enterprise customers. Because we're using Sentry on-premises with a HTTPS proxy that requires authentication we're happy that the SDK supports this now out of the box. 🤩

AFAIU there are two ways to configure the SDK to use a HTTPS proxy:

1. Setting the [`https_proxy` option](https://docs.sentry.io/platforms/python/configuration/options/#https-proxy)
2. Setting the `https_proxy` environment variable

We're using the latter and the authentication credentials are part of the HTTPS proxy URL.

To use the new `proxy_headers` setting we would have to add the following code when initializing the SDK:

```python
from urllib.request import getproxies

import urllib3


def get_proxy_basic_auth():
    https_proxy = getproxies().get("https")
    if https_proxy is None:
        return None
    parsed_url = urllib3.util.parse_url(https_proxy)
    if parsed_url.auth is None:
        return None
    return urllib3.util.make_headers(proxy_basic_auth=parsed_url.auth)
```

Since authentication credentials are pretty common in a HTTPS proxy URL I would like to ask: Is it possible to support the extraction in the SDK?

As the code example above shows this wouldn't introduce any new dependencies.

**Comment by sl0thentr0py** [comment]
@keimlink imo this should be supported upstream in urllib3 then, sentry is just passing through the url

**Comment by keimlink** [comment]
Thanks for the fast reply @sl0thentr0py!

An upstream solution sounds like the best way to solve this!

Found urllib3/urllib3#1999 which proposes to add `Proxy-Authorization` headers using credentials extracted from the URL.
