### ISSUE TITLE
sanic can't show request.header content

### ISSUE THREAD

**Issue by jiamo** [getsentry/sentry-python#720]
After 

```
sentry_sdk.init(
    dsn=user_config['SENTRY_DSN'],
    integrations=[SanicIntegration()],
)
```

and `capture_exception(exception)`

But the browser can't see the `request.header` (which is a dict value)

`request body` can be show but in such warning like 

 
![image](https://user-images.githubusercontent.com/732751/84723519-57329f00-afb8-11ea-913f-6d021ab2cfd6.png)

The first **discared value** is a part of request.header

**Comment by untitaker** [comment]
Which version of Sanic are you using? We just do `dict(request.headers)` and the Sanic documentation does not indicate that those headers are structured/parsed in any way.

**Comment by jiamo** [comment]
sanic 20.3

**Comment by untitaker** [comment]
We only support LTS versions of Sanic. I will make this more clear in the docs but see https://github.com/huge-success/sanic/issues/1532 for more info.

**Comment by untitaker** [comment]
There's a doc PR open which will update the supported versions.

I would suggest to report this bug against Sanic since this seems like something entirely unintended on *their* end. In that case I would also attach a small repro case though.

For reference here is what we do to sanic's request headers: https://github.com/getsentry/sentry-python/blob/1f6743cd89223d5fd9525afafc3230ce3d1e7bd3/sentry_sdk/integrations/sanic.py#L194

We literally just call `dict()` on them and get this back, apparently.
