### ISSUE TITLE
Refactor tox test matrix

### ISSUE THREAD

**Issue by untitaker** [getsentry/sentry-python#743]
This is just a tracking issue for all the problems we have with our current test suite:

* tox is not dealing too well with 200+ virtualenvs.
* *only on my machine*, tox takes 10 seconds for just starting and reading the file. I have no clue why
* creating all virtualenvs takes up 10 GB of disk space

Ideas:

* Merge a couple of virtualenvs into one, so long as python version and package version requirements are not conflicting.
* The above idea is probably not great to implement in tox.ini. We can switch to nox, where the config file is a Python script and as such we can programmatically create the matrix.
* Then again nox itself requires Python 3 installed (while being able to orchestrate any virtualenv)

**Comment by untitaker** [comment]
@rhcarvalho I tried this first idea (merging virtualenvs as long as package versions are not conflicting) and it trims down the size of the test matrix from ~200 to ~60 distinct virtualenvs. I'll open a PR soon. I have some concerns about usability since each individual "job" now gets very large and it's hard to say something like "just run tests for django 1.6" now.

Let me know if you have any other idea to make this work better.

**Comment by rhcarvalho** [comment]
Speeding up CI would be a welcome change. For local dev the need I've had recently was mostly "I want to run this one test in this file", often times in some integration like Django or aiohttp, then I need some env with the right dependencies installed. Often it was enough to have any one version of the dependencies, not necessarily all versions which we test in CI.

**Comment by n1ngu** [comment]
What about dropping old python and framework versions altogether? Actually, I was checking out this repository to ask: don't you have a roadmap to stop supporting those anyway? Lots of python projects have been dropping python<3.6 this year or are about to do it!

Regarding tools and frameworks, I think it can be cumbersome to keep track of each project's release lifecycle. Most are more or less simple or well documented or their communities could provide some hints, but sentry has a lot of integrations anyway. Yet, I think this would also be beneficial for the very integrations, since I am sure there are various fixes for supporting so many version ranges that could be removed! Obviously this would lead to breaking sentry for installs in those old framework versions, but if they are not receiving any framework update they should be pinning and freezing all their dependencies anyway!

As for the very python versions, pythons < 3.6 are way past end of life. I am sure going python-3-only would also mean lots less of quirky patches in the very sentry's core! Namely: all the type hinting system. And that will surely mean happier maintainers and contributors.

I think it is fine to drop support for old versions. People deploying sentry atop them can keep using the existing compatible releases!

**Comment by n1ngu** [comment]
To the extent of my knowledge, as of writing this I think it would be absolutely acceptable to drop support for
- python<3.6
- django<2.2
- flask<0.12
- trytond<5.4

And beyond my knowledge, I think it is probably fine to drop support for
- flask<1.0
- aiohttp<3
- rq<1.0
- pyramid<1.8
- celery<4
- sanic<18

**Comment by untitaker** [comment]
>python<3.6

That is for sure not acceptable. Half of our customers are on Python 2, and we ourselves have just migrated to Python 3.6 in the past year. Don't believe the hype.

**Comment by n1ngu** [comment]
> That is for sure not acceptable. Half of our customers are on Python 2

I can understand that. I myself have some python-2 deployments with sentry and nobody is porting those projects to python-3 anytime soon. Yet, even if I was regularly updating those installations (I'd never dare to, if they weren't abandoned projects they would already run python3 in the first place), I could live with a sentry-sdk frozen to the last version supporting python-2. That's why I suggested that.

As for python 3.4, 3.5 and old framework versions, is the answer the same?

**Comment by untitaker** [comment]
@n1ngu yeah all the other things you brought up are fair game, though I would discuss them in different threads

fundamentally tox is slow for no reason, if we support and test less things that makes the issue hurt less but it's still there

**Comment by antonpirker** [comment]
Quick update: Just had a short talk with @untitaker and the refactoring was aborted. He wanted to replace tox with nox, but nox is not able to do things, we want to have. So we are back on square one of this task.

**Comment by antonpirker** [comment]
The test suite improvements are handled in this PR: https://github.com/getsentry/sentry-python/milestone/11
