### ISSUE TITLE
Logging customizations

### ISSUE THREAD

**Issue by jjlorenzo** [getsentry/sentry-python#84]
In the previous version of the sdk, with django I've specialized logging handlers for sentry, this allows for example, that some specific logging always target sentry.

Now I see that only the level control if the message ends in sentry.

Is there any plan of adding the previous feature to the new client?

**Comment by untitaker** [comment]
Hi @jjlorenzo,

This is still possible. Using [before_breadcrumb and before_send](https://docs.sentry.io/learn/hints/?platform=python) you can filter out unwanted events and breadcrumbs, so you can discard events (or remove breadcrumbs) that come from loggers you don't want. Something like this:

```python
def before_breadcrumb(crumb, hint):
    if crumb.get("category", None) == "unwanted.logger":
        return None
    return crumb

def before_send(event, hint):
    if event.get("logger", None) == "unwanted.logger":
        return None
    return event

sentry_sdk.init(before_send=before_send, before_breadcrumb=before_breadcrumb)
```

Let me know if that's good enough. We try to keep the API surface of particularly the logging integration to a minimum because in raven it was hard to maintain and support.

**Comment by untitaker** [comment]
This will filter out all errors that don't come from loggers as well. I.e. if an exception happens, it will usually not have a logger. `"".startswith("sentry.")` is false.

Try this:

```python
if not event.get("logger", None) or event["logger"].startswith("sentry."):
    return event
return None
```

**Comment by jjlorenzo** [comment]
Roger that, I've updated my code. Really appreciated your help.
