### ISSUE TITLE
Version 0.17.8 broke Celery tasks with custom Task class

### ISSUE THREAD

**Issue by akifd** [getsentry/sentry-python#844]
I am using [tenant-schemas-celery](https://github.com/maciej-gol/tenant-schemas-celery) package, which generates it's own TenantTask (extends celery.app.task.Task) class in it's own CeleryApp (extends celery.Celery). After updating from sentry-sdk from 0.17.7 to 0.17.8 the TenantTask's tenant context switching stopped working. I suspect this is because of the following change in 0.17.8:

```
diff --git a/sentry_sdk/integrations/celery.py b/sentry_sdk/integrations/celery.py
index 1a11d4a..2b51fe1 100644
--- a/sentry_sdk/integrations/celery.py
+++ b/sentry_sdk/integrations/celery.py
@@ -60,9 +60,8 @@ class CeleryIntegration(Integration):
                 # Need to patch both methods because older celery sometimes
                 # short-circuits to task.run if it thinks it's safe.
                 task.__call__ = _wrap_task_call(task, task.__call__)
                 task.run = _wrap_task_call(task, task.run)
-                task.apply_async = _wrap_apply_async(task, task.apply_async)

                 # `build_tracer` is apparently called for every task
                 # invocation. Can't wrap every celery task for every invocation
                 # or we will get infinitely nested wrapper functions.
@@ -71,8 +70,12 @@ class CeleryIntegration(Integration):
             return _wrap_tracer(task, old_build_tracer(name, task, *args, **kwargs))

         trace.build_tracer = sentry_build_tracer

+        from celery.app.task import Task  # type: ignore
+
+        Task.apply_async = _wrap_apply_async(Task.apply_async)
+
         _patch_worker_exit()

         # This logger logs every status of every task that ran on the worker.
         # Meaning that every task's breadcrumbs are full of stuff like "Task
```

I think this problem has to do with this new way of importing celery.app.task.Task. Even though TenantTask extends the celery.app.task.Task, for some reason this change broke the TenantTask logic.

I'm not sure which package this should be fixed in, but I'm bit skeptical about this new import in sentry-sdk, so I'm reporting it here.

Here is my celery.py:

```
from tenant_schemas_celery.app import CeleryApp as TenantAwareCeleryApp


app = TenantAwareCeleryApp()
app.config_from_object('django.conf:settings')
app.autodiscover_tasks()
```

**Comment by untitaker** [comment]
This is curious because the way we monkeypatch should generally work fine with subclasses, and tenanttask does not override apply_async, and the other methods it does override are not called by us. I think there is some magic going on in Celery that I overlooked.

This change was not super mission-critical, I only did it because patching instance methods seemed unnecessary. I'll take a look next week unless there is a second user who has this problem as well.

**Comment by clintmod** [comment]
I think I just ran in to this as well with Flask... here's my code:

```
import celery

from config.celery import DefaultCeleryConfig
from tasks.error_handling import RetryError


# https://flask.palletsprojects.com/en/1.1.x/patterns/celery/
# Run Celery task inside Flask context
# pylint: disable=W0223
class TaskWithFlaskContext(celery.Task):  # noqa: W0223
    autoretry_for = (RetryError,)
    retry_backoff = DefaultCeleryConfig.RETRY_BACKOFF_DELAY_SECONDS
    retry_backoff_max = DefaultCeleryConfig.RETRY_BACKOFF_MAX_SECONDS
    max_retries = DefaultCeleryConfig.MAX_RETRIES
    retry_jitter = DefaultCeleryConfig.RETRY_JITTER

    def __call__(self, *args, **kwargs):
        from config.main import setup_application

        app = setup_application()

        with app.app_context():
            return self.run(*args, **kwargs)

celery = Celery("worker", task_cls="tasks.base:TaskWithFlaskContext")
```

**Comment by clintmod** [comment]
judging by the change mentioned by OP I would assume this code 

```python
from celery.app.task import Task  # type: ignore

Task.apply_async = _wrap_apply_async(Task.apply_async)
```
Is patching a class that we're not using (or that get's replaced).

In this documentation https://flask.palletsprojects.com/en/1.1.x/patterns/celery/#configure
you can see that the class is being replaced `celery.Task = ContextTask`:

```python
from celery import Celery

def make_celery(app):
    celery = Celery(
        app.import_name,
        backend=app.config['CELERY_RESULT_BACKEND'],
        broker=app.config['CELERY_BROKER_URL']
    )
    celery.conf.update(app.config)

    class ContextTask(celery.Task):
        def __call__(self, *args, **kwargs):
            with app.app_context():
                return self.run(*args, **kwargs)

    celery.Task = ContextTask
    return celery
```

**Comment by untitaker** [comment]
Thanks, this snippet helps

**Comment by arcukwasshka** [comment]
Seems like there's a fix coming already, but I'll just leave a note here that this also broke our Celery tasks which are triggered via celery.tasks.periodic_task. We don't have any subclassing going on.

**Comment by untitaker** [comment]
@clintmod (and others) can you verify whether it was actually 0.17.8 that broke your application? I am not able to reproduce issues with custom task classes. I have not tried setting up a Django app with tenant-schemas-celery yet.

It would be greatly apprechiated if somebody could give me a reproducible example in form of a repo where all dependencies are pinned.

**Comment by ur001** [comment]
@untitaker yes, periodic tasks broken by 0.7.18. Periodic task created with `@pediodic_task` by default has class `PeriodicTask` (subclass of Task)

**Comment by arcukwasshka** [comment]
Aye, 0.17.7 works ok and with 0.17.8 it starts breaking.

We don't use tenant-schemas-celery, so the issue *should* be reproducible with plain Django + Celery.

**Comment by untitaker** [comment]
Which celery version is this now? I tried specifically periodic_task now and I am still not able to reproduce.

**Comment by user37596** [comment]
It seems that the version 0.17.7 was also broken, but didn't appear in my local dev environment. After I updated our stage and production environments to 0.17.7, our Celery tasks stopped working because our TenantTask was not handling the context switching anymore. Downgrading to 0.17.6. fixed it. The changelog of 0.17.7 has this:

```Fix a bug under Celery 4.2+ that may have caused disjoint traces or missing transactions.```

**Comment by arcukwasshka** [comment]
With Celery==4.2.2. I can try to provide a testapp but it will take a couple of weeks until I have time to try it out.

The tasks that were failing were using: 

```
from celery.schedules import crontab
from celery.task import periodic_task
...
def repeating_task(task_func):
    run_every_5min = crontab(minute="*/5")
    return periodic_task(run_every=run_every_5min)(task_func)

@repeating_task
def run_tasks():
...
```

**Comment by clintmod** [comment]
I pinned to 0.17.7 and tracing started working again

**Comment by ahmedetefy** [comment]
I have picked this up and I was able to replicate the issue and it seems that the issue seems to occur with the older / deprecated Task class in `celery/task/base.py`, which happens to be the base class for PeriodicTask a common issue with obv
https://github.com/celery/celery/blob/4.3/celery/task/base.py#L126-L128

I believe we are only patching the new Task class 
https://github.com/celery/celery/blob/4.3/celery/app/task.py#L143-L145

Since invoking `apply_async` on a PeriodicTask for example does not go through our patched `apply_async`. I am currently looking into this and will keep everyone updated

**Comment by antonpirker** [comment]
It looks like the problem here is still open.
@clintmod @arcukwasshka @ur001 @user37596 @ahmedetefy could anyone of you please verify this problem still exists with newest Sentry SDK and some current Celery? Thanks!

**Comment by fredbaa** [comment]
I believe this is still happening
```
sentry-sdk==1.5.12
celery[redis]>=4.3,<4.4
```
on celery @periodic_task .. Are there any remediation for this?

**Comment by abhishek-choudhury-callhub** [comment]
@sl0thentr0py, is there a fix planned for this?

**Comment by antonpirker** [comment]
Hello @abhishek-choudhury-callhub !
We have now moved this issue up in prioritization and will make a plan on when we can squeeze fixing this in. 
I will keep you posted!

**Comment by sl0thentr0py** [comment]
@abhishek-choudhury-callhub there are multiple problems in this issue
* tenant-schemas-celery
* periodic_task decorators, which are deprecated since a long time in celery, so you should just be using the newer APIs

which one are you interested in?

**Comment by sl0thentr0py** [comment]
so I finally spent some time trying to repro this today, but was unable to.
@fredbaa since yours was the last comment, I tried this setup in django/celery/redis.

https://github.com/sl0thentr0py/sentry_sample_apps/tree/main/python/django

celery is on `4.3.1` and I used the `@periodic_task` decorator [here](https://github.com/sl0thentr0py/sentry_sample_apps/blob/17e335e7b81ccc10164656b404e5013d2e8dce1a/python/django/sentry/celery.py#L27-L30). I don't see the error you reported and both exception handling and tracing works correctly.

Let me know how I can repro what you are seeing if you want me to investigate this further.

**Comment by fredbaa** [comment]
@sl0thentr0py basically setup 2 celery tasks, one that uses `@periodic_task` and one that just uses the default `@task`. Add a call the latter task using `apply_async` under the periodic task (make sure this is ran on the schedule set, not manually). Is this the setup that you mentioned?

**Comment by antonpirker** [comment]
@fredbaa could you send us a minimal project that can reproduce this?

**Comment by shumakoff** [comment]
Any chance this will be fixed?

**Comment by sl0thentr0py** [comment]
please see the discussion above and give me something to reproduce, there is nothing to fix otherwise.

**Comment by shumakoff** [comment]
I'll try to make minimal project for repro purposes when I have the time, but so far this PR fixed problem for me: 
https://github.com/getsentry/sentry-python/pull/1151

So the issue is real.

**Comment by grahamstreet** [comment]
I too have the run across the same issue.  I upgraded sentry and suddenly had all kinds of issues with Tasks.  Here is the exception,  and I resolved it via the patch in this (PR) commit:

https://github.com/getsentry/sentry-python/pull/1151/commits/3358c4daf80aee3cbede623f6db17bf7026089bd
```

Message
TypeError: unbound method apply_async() must be called with Task instance as first argument (got TaskType instance instead)
Stack Trace(most recent call first)

App Only

Full

Raw
TypeError: unbound method apply_async() must be called with Task instance as first argument (got TaskType instance instead)
  File "django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "django/core/handlers/base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "sentry_sdk/integrations/django/views.py", line 79, in sentry_wrapped_callback
    return callback(request, *args, **kwargs)
  File "django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "switchboard/views.py", line 2455, in recording_complete
    expires=datetime.utcnow() + timedelta(days=1)
  File "sentry_sdk/integrations/celery.py", line 127, in apply_async
    return f(*args, **kwargs)
```

**Comment by antonpirker** [comment]
Cross posting here (from the linked PR I just closed) so that everybody is on the same page:

I again tried to reproduce the problems described here and could not reproduce it. 

I also read the celery source and Sentry is currently patching `celery.app.task.Task` (here: https://github.com/getsentry/sentry-python/blob/master/sentry_sdk/integrations/celery.py#L109)

This class is there in Celery 3-5:
Celery 3: https://github.com/celery/celery/blob/v3.1.26/celery/app/task.py#LL209C20-L209C20
Celery 4: https://github.com/celery/celery/blob/v4.4.7/celery/app/task.py#L144
Celery 5: https://github.com/celery/celery/blob/v5.3.1/celery/app/task.py#L164

Your patch would monkey patch `BaseTask` which is the same thing (see at the very last line of the links posted above)

I am sorry, but I will close this issue/PR.

If there is still something really breaking then please create a new issue with detailed information about versions of Sentry SDK and Celery and an example on how to reproduce it.
