### ISSUE TITLE
`sentry_sdk.tracing.Span` backward incompatibility 

### ISSUE THREAD

**Issue by kodemartin** [getsentry/sentry-python#868]
## Description

Upgraded from`0.14.2` to the latest release `0.19.0` and lost access to `sentry_sdk.tracing.Span.transaction`, as `transaction` is no longer part of the class attributes. 

I see that transactions are handled through  `tracing.Transaction`, and backward compatibility is maintained in the constructor of `Span` when `transaction` is passed as a keyword argument. Also there are workarounds to handle exceptions arising from this issue.

However, the fact remains: If a user tries to set the `Span.transaction` directly, which is permitted as part of the public API in `0.14.2`, will see exceptions raised instead in `0.19.0`.
 
So I would like to raise the following concerns:

* If the project follow semantic versioning, the deprecation of class attributes in minor versions is inconsistent.
* Are there other similar deprecation in the public API that could be somehow emphasized?

**Comment by untitaker** [comment]
Hey @kodemartin, please refer to https://github.com/getsentry/sentry-python/blob/master/CHANGES.md#versioning-policy for our versioning policy. The tldr is that 0.x *can* contain breaking changes, and 0.x.x not. Because the major version is 0, semver allows for this. This is consistent with how most other packages handle version 0.

Generally we try not to break things without deprecation period/warning. As for `span.transaction`, I think this was an oversight on our end, so thanks for bringing this to our attention. Generally anything span/tracing related is still very fresh. At this point we can add a compatibility shim but we'd recommend setting the transaction on `scope`, which will forward properly.

Hope that makes sense.

**Comment by kodemartin** [comment]
Hi @untitaker! Thanks for the prompt reply. I stand indeed corrected with respect to the rules of semver, my apologies. I wasn't aware of the special rules for `0.x.x` versions, nor for the sentry-specific overrides provided in your versioning policy. Thanks for pointing this out to me.

As for the rest, it makes perfect sense. Please feel free to close the issue.

**Comment by untitaker** [comment]
ok thanks. We are open to adding a compat shim if more people are annoyed by this but I think there are not a lot of users who access span directly like that.
