### ISSUE TITLE
Django Template Tag {% sentry_public_dsn %} missing

### ISSUE THREAD

**Issue by SteinRobert** [getsentry/sentry-python#88]
While moving a project from raven-python to sentry-python I noticed, that there is no documentation (and maybe implementation?) for the template tag `{% sentry_public_dsn %}`.
It was available in raven-python - I found it to be quiet handy. 
I hope I am not missing something - or is there a reason that this wasn't implemented?

**Comment by untitaker** [comment]
No particular reason except prioritization of features (this is one of the features that is just easy enough to implement yourself, which is why we've deprioritized it).

Also I personally am unsure if that template tag should just magically become available if somebody runs `sentry_sdk.init`

**Comment by mitsuhiko** [comment]
@SteinRobert we will no longer add this tag because it's no longer needed. The SDK now accepts a public DSN now so if you do want to use the same DSN you can pass it to the template in the render page by passing the DSN from the client options or something to that effect:

```python
from sentry_sdk import last_event_id, Hub
from django.shortcuts import render

def handler500(request, *args, **argv):
    dsn = Hub.current.client.options.dsn
    return render(request, "500.html", {
        'sentry_event_id': last_event_id(),
        'dsn': Hub.current.client.options['dsn'],
    }, status=500)
```

Secondly that tag encouraged users to configure the frontend javascript with the backend dsn as it was available even on non user feedback pages and that is a pattern we do not want users to use.
