### ISSUE TITLE
Question about automatic release detection

### ISSUE THREAD

**Issue by rafikdraoui** [getsentry/sentry-python#908]
The python SDK uses [`git rev-parse --short HEAD`](https://github.com/getsentry/sentry-python/blob/6f1aa1ff8046a17af71158ac0e4302deb098a44c/sentry_sdk/utils.py#L67) to determine a release from a git repository. `sentry-cli releases propose-version` returns the full-length hash for `HEAD`.

If I were to use `sentry-cli`'s proposed version to make a release when deploying, and let `sentry-python` automatically detect the release at runtime, would they be both referring to the same release? On the one hand, the hash are not exactly equal, so they could be considered different, but on the other hand, they semantically are "the same" according to `git`.

One way to find out would be to actually try it, but I still haven't configured releases on my project and thought I might try to see if that would be a viable option before going too deep into it 😃

**Comment by untitaker** [comment]
@mitsuhiko can you look into this? You added this functionality and know most about releases at the moment.

also cc @matejminar

**Comment by petarmaric** [comment]
Just ran into this same issue for my client - when using https://github.com/marketplace/actions/sentry-release within our GitHub actions-powered CD workflow to automatically create a new Sentry release we get an automatically detected release such as `365020454471` in the Sentry dashboard.

However, the current [git-based automatic detection](https://github.com/getsentry/sentry-python/blob/0.19.5/sentry_sdk/utils.py#L67) returns a different release string `3650204`, for the same deployment.

Because of this we keep getting two "different" releases in the Sentry dashboard for the same deployment, where one receives  errors/events (git-based automatic detection, on the server itself), but the other has relevant codebase/author/commits info (GitHub actions automatic detection, during deployment). Any idea how to go about this @untitaker and @mitsuhiko ?

**Comment by petarmaric** [comment]
ping @untitaker
