### ISSUE TITLE
Sentry not logging chain exception `raise Exception() from e`

### ISSUE THREAD

**Issue by CircleOnCircles** [getsentry/sentry-python#970]
Sentry not logging chain exception `raise Exception() from e`

for example

```python
class FooFail(Exception):
	pass

try:
	1/0
except Exception as e:
	raise FooFail('a foo exception.') from e
```

Since `e` contain the information use to identify cause of root exception. It is very important to see chain exception detail. The missing of detail in Sentry issue panel.

**Comment by untitaker** [comment]
Both exceptions should show on the details page.

**Comment by CircleOnCircles** [comment]
![image](https://user-images.githubusercontent.com/8089231/104480208-e9566080-55f6-11eb-90da-fd0fe214114e.png)

It is not even show the type of exception.

**Comment by CircleOnCircles** [comment]
Sorry, you are right. my code is a special case. 
![image](https://user-images.githubusercontent.com/8089231/104481437-5fa79280-55f8-11eb-819c-057e9c7ec7f6.png)

**Comment by CircleOnCircles** [comment]
But, it did happen in my code. I cannot reveal my code.

**Comment by untitaker** [comment]
If you see a plaintext traceback you will have a bad time for a lot of reasons:

1. those events do not group well into issues as we don't have semantic knowledge of the stacktrace (it's just a string to the server)
2. apparently, and this is new to me, chained exceptions can also go missing

Usually this is caused by code that stringifies the exception using the `traceback` module and then logs it. You can find out which logger that is using the `logger` event tag.
