### ISSUE TITLE
Pyramid support

### ISSUE THREAD

**Issue by CasperCL** [getsentry/sentry-python#98]
[Pyramid](https://trypyramid.com/) was previously supported by raven. It would be great to see support for it in this client. Is this perhaps already on the roadmap?

Also if there is any documentation on how to write an integration I might be tempted to contribute.

**Comment by untitaker** [comment]
Hi, we generally want to move out integrations into separate packages.

Integrations don't have a large interface they need to implement: There's the [`Integration`[(https://getsentry.github.io/sentry-python/integrations/index.html#sentry_sdk.integrations.Integration) class with a single `install` function that can do anything. In most integrations this means registering/hooking/patching into global signal handlers to receive exceptions.

I would encourage to try integrating Pyramid with this SDK in a separate package, but with a few caveats:

* You probably want to use `sentry_sdk.integrations._wsgi` like Flask and Django do, but that is currently an unstable API. Stabilizing this is on the roadmap.
* We don't have much documentation about how to write integrations because the only prerequisite for getting started is subclassing `Integration`. But that also means that you'll have to look into existing code to see what is idiomatic in the context of this SDK.

**Comment by CasperCL** [comment]
Thanks for you reply and the pointers. It doesn't seem like Pyramid integrates as nicely as Flask or Django and since the `_wsgi` module is subject to change I think I'm going to withhold from implementing the integration for now. If I change my mind, I'll make sure to create a separate package for it.

**Comment by untitaker** [comment]
Note though that this is not fully set in stone yet, we are definetly open to changes of plan, should the demand for a native Pyramid integration be there :)

**Comment by untitaker** [comment]
Pyramid support is happening very soon

**Comment by untitaker** [comment]
actually as soon as GitHub is recovered and processing that webhook 😬

**Comment by untitaker** [comment]
@CasperCL happy to say that 0.5.0 will include pyramid support! Feel free to open more feature requests for whatever you see missing. We decided to take a different approach on integrations

**Comment by CasperCL** [comment]
That’s great news! Thanks for taking the time to create an integration.
